import type { Exercise, Person, Weekday, WorkoutDay, WorkoutExercise } from './types';

export const dayLabels: Record<Weekday, string> = {
  seg: 'Seg',
  ter: 'Ter',
  qua: 'Qua',
  qui: 'Qui',
  sex: 'Sex',
  sab: 'Sáb',
  dom: 'Dom',
};

export const dayNames: Record<Weekday, string> = {
  seg: 'segunda-feira',
  ter: 'terça-feira',
  qua: 'quarta-feira',
  qui: 'quinta-feira',
  sex: 'sexta-feira',
  sab: 'sábado',
  dom: 'domingo',
};

const aceLibrary = 'https://www.acefitness.org/resources/everyone/exercise-library/';

export const exerciseCatalog: Record<string, Exercise> = {
  'chest-press': {
    id: 'chest-press', name: 'Chest press na máquina', category: 'Peito', primary: 'Peitoral maior',
    secondary: ['Tríceps', 'Deltoide anterior'], equipment: 'Máquina de peito', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Ajuste o banco para que as alças fiquem na linha do meio do peito. Mantenha costas e cabeça apoiadas, pés firmes no chão.',
    execution: ['Segure as alças com os punhos alinhados aos antebraços.', 'Empurre para frente sem travar os cotovelos.', 'Retorne devagar até sentir alongar o peito, sem deixar a carga bater.'],
    breathing: 'Solte o ar ao empurrar e inspire ao voltar.',
    commonMistakes: ['Elevar os ombros em direção às orelhas', 'Desencostar as costas do banco', 'Usar impulso para fechar a repetição'],
    beginnersTips: ['Comece com a menor carga que permita controlar as duas fases.', 'Peça ajuda para ajustar banco e amplitude.'],
    easierAlternative: 'Flexão inclinada apoiando as mãos em um banco firme.', substitutes: ['incline-press', 'pushdown'],
  },
  'cable-row': {
    id: 'cable-row', name: 'Remada sentada no cabo', category: 'Costas', primary: 'Latíssimo do dorso',
    secondary: ['Romboides', 'Bíceps', 'Deltoide posterior'], equipment: 'Cabo com triângulo', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Sente-se com joelhos levemente flexionados, peito aberto e coluna neutra. Segure o triângulo com os braços estendidos.',
    execution: ['Puxe as alças em direção ao umbigo conduzindo pelos cotovelos.', 'Pause quando as escápulas se aproximarem.', 'Estenda os braços controlando o retorno, sem arredondar a lombar.'],
    breathing: 'Expire na puxada e inspire na volta.',
    commonMistakes: ['Balançar o tronco para criar impulso', 'Encolher os ombros', 'Deixar o joelho travado'],
    beginnersTips: ['Imagine que os cotovelos vão para trás, não as mãos.', 'Use uma carga que permita pausar no final.'],
    easierAlternative: 'Remada com elástico preso em um ponto estável.', substitutes: ['lat-pulldown', 'chest-supported-row'],
  },
  'lat-pulldown': {
    id: 'lat-pulldown', name: 'Puxada frontal', category: 'Costas', primary: 'Latíssimo do dorso',
    secondary: ['Bíceps', 'Romboides'], equipment: 'Polia alta', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Ajuste o apoio das coxas. Sente-se alto, peito aberto e mãos um pouco além da largura dos ombros.',
    execution: ['Puxe a barra em direção à parte alta do peito.', 'Mantenha cotovelos apontando para baixo e não atrás do corpo.', 'Suba a barra lentamente até quase estender os braços.'],
    breathing: 'Expire ao puxar e inspire ao subir.',
    commonMistakes: ['Puxar a barra atrás da nuca', 'Inclinar muito o tronco', 'Soltar a carga rapidamente'],
    beginnersTips: ['Pense em colocar os cotovelos nos bolsos.', 'A amplitude confortável é melhor que uma carga alta.'],
    easierAlternative: 'Puxada com elástico em pé.', substitutes: ['cable-row', 'assisted-pullup'],
  },
  'shoulder-press': {
    id: 'shoulder-press', name: 'Desenvolvimento na máquina', category: 'Ombros', primary: 'Deltoides',
    secondary: ['Tríceps', 'Peitoral superior'], equipment: 'Máquina de ombros', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Encoste costas e cabeça. Posicione as alças um pouco abaixo da altura dos ombros, com punhos neutros.',
    execution: ['Empurre as alças para cima em uma linha confortável.', 'Pare antes de travar os cotovelos.', 'Desça até as alças ficarem próximas aos ombros.'],
    breathing: 'Expire na subida e inspire na descida.',
    commonMistakes: ['Arquear excessivamente a lombar', 'Baixar além da amplitude confortável', 'Impulsionar com as pernas'],
    beginnersTips: ['Mantenha as costelas para baixo e o abdômen levemente ativo.', 'Ajuste o banco antes de escolher a carga.'],
    easierAlternative: 'Elevação lateral com halteres leves.', substitutes: ['lateral-raise', 'incline-press'],
  },
  'triceps-pushdown': {
    id: 'triceps-pushdown', name: 'Tríceps na polia', category: 'Braços', primary: 'Tríceps braquial',
    secondary: ['Core'], equipment: 'Polia alta com corda', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique em pé com joelhos destravados, cotovelos próximos ao corpo e ombros relaxados.',
    execution: ['Empurre a corda até quase estender os cotovelos.', 'Separe levemente as pontas no final.', 'Volte só até o antebraço ficar perto da vertical, sem mover os cotovelos.'],
    breathing: 'Expire ao empurrar e inspire ao voltar.',
    commonMistakes: ['Abrir os cotovelos', 'Inclinar o tronco para usar o peso', 'Mover os ombros'],
    beginnersTips: ['Use uma carga que permita manter os cotovelos quietos.', 'Controle especialmente o retorno.'],
    easierAlternative: 'Tríceps com elástico leve.', substitutes: ['overhead-triceps', 'chest-press'],
  },
  'dead-bug': {
    id: 'dead-bug', name: 'Dead bug', category: 'Core', primary: 'Abdômen profundo',
    secondary: ['Flexores do quadril', 'Oblíquos'], equipment: 'Colchonete', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Deite de costas, quadris e joelhos a 90 graus, braços apontando para o teto. Mantenha a lombar suave contra o chão.',
    execution: ['Estenda lentamente uma perna e o braço oposto.', 'Pare antes de perder o contato da lombar com o chão.', 'Volte ao centro e alterne os lados.'],
    breathing: 'Expire ao estender e inspire ao retornar.',
    commonMistakes: ['Deixar a lombar arquear', 'Acelerar a troca dos lados', 'Prender a respiração'],
    beginnersTips: ['Faça apenas o movimento das pernas se for mais fácil.', 'Diminua a amplitude antes de perder o controle.'],
    easierAlternative: 'Marcha deitada, movendo uma perna por vez.', substitutes: ['plank', 'pallof-press'],
  },
  'leg-press': {
    id: 'leg-press', name: 'Leg press 45°', category: 'Pernas', primary: 'Quadríceps',
    secondary: ['Glúteos', 'Posterior de coxa'], equipment: 'Leg press', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Sente-se com quadril e costas apoiados. Pés na largura dos ombros, no meio da plataforma. Libere a trava apenas com controle.',
    execution: ['Desça a plataforma flexionando joelhos e quadris.', 'Pare quando a lombar começar a perder o apoio.', 'Empurre pelo meio do pé e volte sem travar os joelhos.'],
    breathing: 'Inspire na descida e expire ao empurrar.',
    commonMistakes: ['Deixar os joelhos colapsarem para dentro', 'Descer além do controle', 'Travar os joelhos no topo'],
    beginnersTips: ['Faça algumas repetições sem carga para sentir o percurso.', 'Mantenha o mesmo caminho dos joelhos durante todo o movimento.'],
    easierAlternative: 'Agachamento para um banco alto.', substitutes: ['goblet-squat', 'hack-squat'],
  },
  'leg-curl': {
    id: 'leg-curl', name: 'Flexora sentada', category: 'Pernas', primary: 'Posterior de coxa',
    secondary: ['Gastrocnêmio'], equipment: 'Cadeira flexora', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Ajuste o eixo da máquina ao seu joelho e apoie as costas. A almofada deve repousar logo acima do tornozelo.',
    execution: ['Flexione os joelhos levando a almofada para baixo.', 'Faça uma pausa curta sem tirar o quadril do banco.', 'Retorne de maneira lenta até quase estender os joelhos.'],
    breathing: 'Expire ao flexionar e inspire ao retornar.',
    commonMistakes: ['Levantar o quadril do assento', 'Chutar a almofada', 'Usar amplitude que cause dor no joelho'],
    beginnersTips: ['Ajuste a máquina antes de aumentar a carga.', 'Conte dois segundos na volta.'],
    easierAlternative: 'Flexão de joelho com bola ou toalha no chão.', substitutes: ['romanian-deadlift', 'leg-extension'],
  },
  'goblet-squat': {
    id: 'goblet-squat', name: 'Agachamento com halter', category: 'Pernas', primary: 'Quadríceps',
    secondary: ['Glúteos', 'Core'], equipment: 'Halter', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Segure um halter junto ao peito, pés confortáveis e peito aberto. Pense em apoiar o peso no meio dos pés.',
    execution: ['Leve quadril para trás e flexione os joelhos.', 'Desça apenas enquanto mantiver o tronco e os pés estáveis.', 'Empurre o chão para voltar, mantendo joelhos alinhados aos pés.'],
    breathing: 'Inspire na descida e expire ao subir.',
    commonMistakes: ['Juntar os joelhos', 'Tirar os calcanhares do chão', 'Descer rápido demais'],
    beginnersTips: ['Use um banco como referência de profundidade.', 'Comece sem peso se ainda estiver aprendendo o caminho.'],
    easierAlternative: 'Agachamento no banco sem carga.', substitutes: ['leg-press', 'hack-squat'],
  },
  'hip-thrust': {
    id: 'hip-thrust', name: 'Elevação de quadril na máquina', category: 'Glúteos', primary: 'Glúteo máximo',
    secondary: ['Posterior de coxa', 'Core'], equipment: 'Máquina de hip thrust', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Apoie a lombar no encosto ou banco indicado, queixo levemente recolhido e pés afastados na largura do quadril.',
    execution: ['Empurre o chão com os pés e eleve o quadril.', 'Finalize com o corpo alinhado, contraindo glúteos sem arquear a lombar.', 'Desça controlando até o quadril quase tocar o apoio.'],
    breathing: 'Expire na subida e inspire na descida.',
    commonMistakes: ['Compensar com a lombar', 'Abrir demais as costelas', 'Colocar os pés longe demais'],
    beginnersTips: ['Pratique primeiro sem carga.', 'No topo, pense em aproximar o púbis do umbigo.'],
    easierAlternative: 'Elevação de quadril no chão.', substitutes: ['goblet-squat', 'romanian-deadlift'],
  },
  'calf-raise': {
    id: 'calf-raise', name: 'Elevação de panturrilha', category: 'Pernas', primary: 'Gastrocnêmio',
    secondary: ['Sóleo'], equipment: 'Máquina ou degrau', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique estável com o antepé apoiado e calcanhares livres, segurando em algo firme quando necessário.',
    execution: ['Eleve os calcanhares até o máximo confortável.', 'Pause brevemente no alto.', 'Desça devagar sentindo alongar a panturrilha.'],
    breathing: 'Respire de forma contínua, expirando na subida.',
    commonMistakes: ['Fazer movimentos curtos e rápidos', 'Perder a estabilidade do tornozelo', 'Usar impulso'],
    beginnersTips: ['Priorize amplitude e controle.', 'Comece segurando em um apoio.'],
    easierAlternative: 'Elevação de panturrilha sentado sem carga.', substitutes: ['leg-extension', 'goblet-squat'],
  },
  'plank': {
    id: 'plank', name: 'Prancha frontal', category: 'Core', primary: 'Abdômen',
    secondary: ['Glúteos', 'Ombros'], equipment: 'Colchonete', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Apoie antebraços e joelhos ou pés. Cotovelos ficam abaixo dos ombros, pescoço alinhado.',
    execution: ['Contraia abdômen e glúteos.', 'Mantenha uma linha confortável dos ombros ao quadril.', 'Pare antes de a lombar ceder ou a respiração travar.'],
    breathing: 'Respire devagar e continuamente, sem prender o ar.',
    commonMistakes: ['Deixar o quadril cair', 'Empurrar o chão com os ombros encolhidos', 'Segurar a respiração'],
    beginnersTips: ['Comece com os joelhos apoiados.', 'É melhor sustentar 20 segundos com qualidade do que forçar 60.'],
    easierAlternative: 'Prancha com joelhos no chão.', substitutes: ['dead-bug', 'pallof-press'],
  },
  'incline-press': {
    id: 'incline-press', name: 'Supino inclinado com halteres', category: 'Peito', primary: 'Peitoral superior',
    secondary: ['Tríceps', 'Deltoide anterior'], equipment: 'Banco inclinado + halteres', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Banco em inclinação moderada, pés no chão e halteres na altura do peito. Escápulas apoiadas e ombros longe das orelhas.',
    execution: ['Empurre os halteres para cima mantendo punhos sobre os cotovelos.', 'Aproxime sem bater os halteres.', 'Desça com cotovelos em um ângulo confortável, sem perder o apoio.'],
    breathing: 'Expire na subida e inspire na descida.',
    commonMistakes: ['Abrir os cotovelos em 90 graus', 'Descer rápido', 'Usar halteres difíceis de posicionar'],
    beginnersTips: ['Peça ajuda para colocar os halteres no lugar.', 'Comece com pouca carga para dominar a trajetória.'],
    easierAlternative: 'Chest press na máquina.', substitutes: ['chest-press', 'pushdown'],
  },
  'face-pull': {
    id: 'face-pull', name: 'Face pull', category: 'Ombros', primary: 'Deltoide posterior',
    secondary: ['Romboides', 'Manguito rotador'], equipment: 'Cabo com corda', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Polia na altura do rosto, postura alta, braços estendidos e corda segura com polegares apontando para trás.',
    execution: ['Puxe a corda na direção do rosto, abrindo as mãos.', 'Pense em girar os braços sem elevar os ombros.', 'Retorne lentamente mantendo o tronco parado.'],
    breathing: 'Expire na puxada e inspire na volta.',
    commonMistakes: ['Usar uma carga alta', 'Inclinar o corpo para trás', 'Forçar a amplitude do ombro'],
    beginnersTips: ['Faça leve e com pausa.', 'O movimento é para sentir a parte posterior do ombro e as costas altas.'],
    easierAlternative: 'Abertura reversa com elástico leve.', substitutes: ['lateral-raise', 'cable-row'],
  },
  'dumbbell-curl': {
    id: 'dumbbell-curl', name: 'Rosca alternada', category: 'Braços', primary: 'Bíceps',
    secondary: ['Braquial', 'Antebraço'], equipment: 'Halteres', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique em pé com halteres ao lado do corpo, palmas voltadas para frente e cotovelos próximos ao tronco.',
    execution: ['Flexione um cotovelo sem mover o ombro.', 'Suba até perto do peito sem perder o punho neutro.', 'Desça devagar antes de trocar o lado.'],
    breathing: 'Expire na subida e inspire na descida.',
    commonMistakes: ['Balançar o tronco', 'Projetar o cotovelo para frente', 'Descer sem controle'],
    beginnersTips: ['Imagine que o cotovelo está preso ao corpo.', 'Alterne os lados para focar na técnica.'],
    easierAlternative: 'Rosca com elástico leve.', substitutes: ['cable-curl', 'triceps-pushdown'],
  },
  'overhead-triceps': {
    id: 'overhead-triceps', name: 'Tríceps acima da cabeça', category: 'Braços', primary: 'Tríceps braquial',
    secondary: ['Core'], equipment: 'Cabo ou halter', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique sentado ou em pé, braços acima da cabeça e cotovelos apontando para frente, sem abrir demais.',
    execution: ['Flexione os cotovelos levando as mãos atrás da cabeça.', 'Mantenha os braços relativamente parados.', 'Estenda sem travar e volte devagar.'],
    breathing: 'Expire ao estender e inspire ao flexionar.',
    commonMistakes: ['Abrir muito os cotovelos', 'Arquear a lombar', 'Forçar a amplitude do ombro'],
    beginnersTips: ['Escolha o cabo se tiver dificuldade para posicionar um halter.', 'Use uma carga bem menor que no pushdown.'],
    easierAlternative: 'Tríceps na polia com corda.', substitutes: ['triceps-pushdown', 'chest-press'],
  },
  'pallof-press': {
    id: 'pallof-press', name: 'Pallof press', category: 'Core', primary: 'Core anti-rotação',
    secondary: ['Oblíquos', 'Ombros'], equipment: 'Cabo ou elástico', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique de lado para a polia, pés afastados e mãos junto ao peito. Ajuste a distância para sentir uma tensão moderada.',
    execution: ['Empurre as mãos para longe do peito.', 'Resista à rotação do tronco e mantenha quadril alinhado.', 'Traga as mãos de volta sem perder a postura.'],
    breathing: 'Expire ao estender e inspire ao retornar.',
    commonMistakes: ['Girar o tronco em direção ao cabo', 'Usar impulso', 'Travar os joelhos'],
    beginnersTips: ['Comece com pouca carga e tempo de pausa curto.', 'Reduza a distância da polia se perder o alinhamento.'],
    easierAlternative: 'Pallof press com elástico leve.', substitutes: ['dead-bug', 'plank'],
  },
  'romanian-deadlift': {
    id: 'romanian-deadlift', name: 'Levantamento romeno com halteres', category: 'Posterior', primary: 'Posterior de coxa',
    secondary: ['Glúteos', 'Lombar'], equipment: 'Halteres', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Pés na largura do quadril, halteres à frente das coxas, costas longas e joelhos levemente destravados.',
    execution: ['Leve o quadril para trás mantendo os halteres próximos às pernas.', 'Desça só até sentir tensão no posterior sem arredondar a coluna.', 'Empurre o chão e estenda o quadril para voltar.'],
    breathing: 'Inspire ao descer e expire ao subir.',
    commonMistakes: ['Agachar em vez de fazer a dobradiça do quadril', 'Afastar os halteres das pernas', 'Arredondar a lombar'],
    beginnersTips: ['Pratique a dobradiça com um cabo de vassoura nas costas.', 'Pare antes de a mobilidade limitar a postura.'],
    easierAlternative: 'Dobradiça do quadril sem carga.', substitutes: ['leg-curl', 'hip-thrust'],
  },
  'leg-extension': {
    id: 'leg-extension', name: 'Cadeira extensora', category: 'Pernas', primary: 'Quadríceps',
    secondary: ['Core'], equipment: 'Cadeira extensora', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Ajuste o eixo ao joelho e o rolo na frente do tornozelo. Sente-se com lombar apoiada e joelhos alinhados.',
    execution: ['Estenda os joelhos até uma posição confortável.', 'Pause brevemente sem travar.', 'Desça com controle até o início.'],
    breathing: 'Expire na extensão e inspire ao retornar.',
    commonMistakes: ['Chutar a carga', 'Desencostar o quadril', 'Travar o joelho com força'],
    beginnersTips: ['Faça uma amplitude sem dor.', 'Ajuste o rolo para não pressionar a canela.'],
    easierAlternative: 'Extensão de joelho sentado sem carga.', substitutes: ['leg-press', 'goblet-squat'],
  },
  'hip-abduction': {
    id: 'hip-abduction', name: 'Abdutora na máquina', category: 'Glúteos', primary: 'Glúteo médio',
    secondary: ['Glúteo máximo', 'Abdutores do quadril'], equipment: 'Máquina abdutora', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Sente-se com costas apoiadas, pés nos apoios e joelhos alinhados com o eixo indicado pela máquina.',
    execution: ['Abra as pernas contra a resistência sem inclinar o tronco.', 'Pause na abertura confortável.', 'Retorne devagar sem deixar as placas baterem.'],
    breathing: 'Expire ao abrir e inspire ao voltar.',
    commonMistakes: ['Usar balanço do tronco', 'Abrir além da mobilidade', 'Soltar a volta'],
    beginnersTips: ['Comece com uma carga que permita segurar a abertura.', 'A qualidade da volta importa tanto quanto a abertura.'],
    easierAlternative: 'Abdução deitado de lado.', substitutes: ['hip-thrust', 'goblet-squat'],
  },
  'assisted-pullup': {
    id: 'assisted-pullup', name: 'Puxada na máquina assistida', category: 'Costas', primary: 'Latíssimo do dorso',
    secondary: ['Bíceps', 'Core'], equipment: 'Máquina de barra assistida', difficulty: 'Intermediário', sourceUrl: aceLibrary,
    startingPosture: 'Apoie os joelhos, segure as barras e mantenha o peito alto. Escolha assistência suficiente para controlar o movimento.',
    execution: ['Puxe o corpo levando o peito em direção às mãos.', 'Evite encolher os ombros e pause no alto.', 'Desça até quase estender os cotovelos, sem despencar.'],
    breathing: 'Expire na subida e inspire na descida.',
    commonMistakes: ['Balançar o corpo', 'Projetar o queixo para alcançar a barra', 'Descer sem controle'],
    beginnersTips: ['Prefira mais assistência e amplitude completa.', 'Peça instrução para entrar e sair da máquina com segurança.'],
    easierAlternative: 'Puxada frontal na polia.', substitutes: ['lat-pulldown', 'cable-row'],
  },
  'cable-curl': {
    id: 'cable-curl', name: 'Rosca na polia', category: 'Braços', primary: 'Bíceps',
    secondary: ['Braquial', 'Antebraço'], equipment: 'Polia baixa + barra curta', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique estável, segurando a barra com palmas para cima e cotovelos próximos ao corpo.',
    execution: ['Flexione os cotovelos sem mover os ombros.', 'Aproxime a barra do peito dentro da amplitude confortável.', 'Retorne devagar mantendo tensão no cabo.'],
    breathing: 'Expire na subida e inspire na volta.',
    commonMistakes: ['Inclinar o tronco para trás', 'Estender completamente de forma brusca', 'Usar o quadril'],
    beginnersTips: ['Fique perto da polia para não ser puxado.', 'Use o cabo para aprender a controlar a volta.'],
    easierAlternative: 'Rosca alternada com halter leve.', substitutes: ['dumbbell-curl', 'triceps-pushdown'],
  },
  'chest-supported-row': {
    id: 'chest-supported-row', name: 'Remada com peito apoiado', category: 'Costas', primary: 'Romboides',
    secondary: ['Latíssimo do dorso', 'Bíceps'], equipment: 'Banco inclinado + halteres', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Deite com o peito apoiado no banco inclinado, pés firmes e halteres pendendo abaixo dos ombros.',
    execution: ['Puxe os halteres conduzindo pelos cotovelos.', 'Aproxime escápulas sem levantar o peito do banco.', 'Desça os pesos até quase estender os braços.'],
    breathing: 'Expire na puxada e inspire na descida.',
    commonMistakes: ['Levantar o tronco', 'Encolher os ombros', 'Bater os pesos no banco'],
    beginnersTips: ['O apoio ajuda a evitar balanço.', 'Escolha halteres leves para manter o peito encostado.'],
    easierAlternative: 'Remada sentada no cabo.', substitutes: ['cable-row', 'lat-pulldown'],
  },
  'hack-squat': {
    id: 'hack-squat', name: 'Agachamento no hack', category: 'Pernas', primary: 'Quadríceps',
    secondary: ['Glúteos', 'Posterior de coxa'], equipment: 'Máquina hack', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Apoie costas e ombros, pés na plataforma e joelhos apontando para a mesma direção dos pés.',
    execution: ['Desça flexionando joelhos e quadris sem tirar as costas do apoio.', 'Pare antes de perder a posição confortável.', 'Empurre a plataforma mantendo joelhos destravados.'],
    breathing: 'Inspire na descida e expire ao subir.',
    commonMistakes: ['Deixar os joelhos fecharem', 'Tirar os calcanhares do apoio', 'Travar os joelhos no final'],
    beginnersTips: ['Peça para alguém mostrar as travas da máquina.', 'Comece somente com o peso da máquina.'],
    easierAlternative: 'Leg press com pouca carga.', substitutes: ['leg-press', 'goblet-squat'],
  },
  'lateral-raise': {
    id: 'lateral-raise', name: 'Elevação lateral', category: 'Ombros', primary: 'Deltoide lateral',
    secondary: ['Trapézio superior', 'Core'], equipment: 'Halteres', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique em pé com halteres ao lado do corpo, braços levemente flexionados e ombros relaxados.',
    execution: ['Eleve os braços para os lados até a altura confortável dos ombros.', 'Mantenha mãos e cotovelos em uma linha suave.', 'Desça lentamente sem descansar a carga no corpo.'],
    breathing: 'Expire ao subir e inspire ao descer.',
    commonMistakes: ['Usar balanço', 'Elevar os ombros', 'Escolher carga alta demais'],
    beginnersTips: ['Halteres leves funcionam melhor.', 'Pare no ponto em que o ombro mantém espaço e controle.'],
    easierAlternative: 'Elevação lateral com elástico leve.', substitutes: ['shoulder-press', 'face-pull'],
  },
};

const ex = (exerciseId: string, sets: number, reps: string, rest: number, cue: string): WorkoutExercise => ({ exerciseId, sets, reps, rest, cue });

export const workoutPlans: Record<Person, WorkoutDay[]> = {
  breno: [
    {
      id: 'breno-upper-a', person: 'breno', title: 'Base de cima', label: 'Peito + costas', objective: 'Construir força de base no tronco com movimentos estáveis.',
      muscleGroups: ['Peito', 'Costas', 'Ombros', 'Tríceps', 'Core'], duration: '52–60 min', warmup: ['5–7 min de caminhada ou bike leve', '1 série leve de cada primeiro exercício', 'Mobilidade suave de ombros e coluna torácica'], finish: '2–3 min caminhando devagar e respiração confortável.', safety: 'Mantenha 2–3 repetições “na reserva” nas primeiras semanas.',
      exercises: [ex('chest-press', 3, '8–12', 90, 'Empurre com o peito aberto, sem travar os cotovelos.'), ex('cable-row', 3, '8–12', 90, 'Puxe pelos cotovelos e pause as escápulas.'), ex('lat-pulldown', 3, '8–12', 90, 'Traga a barra ao peito, nunca atrás da nuca.'), ex('shoulder-press', 2, '10–12', 75, 'Costas apoiadas e costelas controladas.'), ex('triceps-pushdown', 2, '10–15', 60, 'Cotovelos quietos ao lado do corpo.'), ex('dead-bug', 3, '8–10/lado', 45, 'Só aumente a amplitude se a lombar ficar estável.')],
    },
    {
      id: 'breno-lower-a', person: 'breno', title: 'Pernas base', label: 'Quadríceps + glúteos', objective: 'Treinar pernas completas com ritmo controlado e segurança.',
      muscleGroups: ['Quadríceps', 'Posterior', 'Glúteos', 'Panturrilhas', 'Core'], duration: '50–58 min', warmup: ['5–7 min de bike leve', '8 agachamentos para um banco, sem carga', '1 série de adaptação no leg press'], finish: 'Caminhada leve até a respiração normalizar; alongamento suave opcional.', safety: 'A profundidade é limitada pela sua postura, não pela pressa de descer mais.',
      exercises: [ex('leg-press', 3, '8–12', 120, 'Joelhos acompanham a linha dos pés.'), ex('leg-curl', 3, '10–12', 90, 'Quadril permanece apoiado.'), ex('goblet-squat', 2, '10–12', 90, 'Use o banco como referência.'), ex('hip-thrust', 2, '10–12', 90, 'Finalize com glúteos, não com a lombar.'), ex('calf-raise', 2, '12–15', 60, 'Pausa curta no alto.'), ex('plank', 3, '20–40 s', 45, 'Respire sem deixar o quadril cair.')],
    },
    {
      id: 'breno-upper-b', person: 'breno', title: 'Tronco completo', label: 'Costas + braços', objective: 'Reforçar puxadas, empurradas e estabilidade dos ombros.',
      muscleGroups: ['Costas', 'Peito', 'Bíceps', 'Tríceps', 'Ombros', 'Core'], duration: '52–60 min', warmup: ['5 min de elíptico leve', 'Movimentos circulares controlados para ombros', '1 série leve de supino e remada'], finish: 'Respiração leve e mobilidade de peito/ombros sem forçar.', safety: 'Prefira repetir com técnica consistente a aumentar carga a cada sessão.',
      exercises: [ex('incline-press', 3, '8–12', 90, 'Halteres sobem sobre os cotovelos.'), ex('cable-row', 3, '8–12', 90, 'Tronco firme e retorno lento.'), ex('chest-supported-row', 2, '10–12', 75, 'Mantenha o peito apoiado.'), ex('face-pull', 2, '12–15', 60, 'Leve a corda ao rosto sem encolher os ombros.'), ex('dumbbell-curl', 2, '10–12', 60, 'Cotovelo fica próximo ao corpo.'), ex('overhead-triceps', 2, '10–12', 60, 'Amplitude confortável para o ombro.'), ex('pallof-press', 2, '10/lado', 45, 'Resista à rotação do tronco.')],
    },
    {
      id: 'breno-lower-b', person: 'breno', title: 'Pernas posterior', label: 'Posterior + pernas', objective: 'Dar atenção à cadeia posterior e completar o trabalho de pernas.',
      muscleGroups: ['Posterior', 'Glúteos', 'Quadríceps', 'Panturrilhas', 'Core'], duration: '48–56 min', warmup: ['5–7 min de caminhada inclinada leve', 'Dobradiça de quadril sem carga', '1 série leve de flexora'], finish: 'Caminhe 3 minutos e faça alongamentos confortáveis, sem dor.', safety: 'No romeno, a amplitude termina quando a coluna quer arredondar.',
      exercises: [ex('romanian-deadlift', 3, '8–12', 120, 'Quadril para trás; halteres próximos às pernas.'), ex('hack-squat', 3, '8–12', 120, 'Use a amplitude que mantém costas apoiadas.'), ex('leg-extension', 2, '10–15', 75, 'Subida controlada e sem travar.'), ex('hip-abduction', 2, '12–15', 60, 'Segure um segundo na abertura.'), ex('calf-raise', 2, '12–15', 60, 'Movimento completo e estável.'), ex('dead-bug', 3, '8–10/lado', 45, 'Costelas e lombar continuam organizadas.')],
    },
  ],
  leticia: [
    {
      id: 'leticia-lower-a', person: 'leticia', title: 'Pernas & glúteos', label: 'Quadríceps + glúteos', objective: 'Começar a semana com foco em pernas, estabilidade e core.',
      muscleGroups: ['Quadríceps', 'Glúteos', 'Posterior', 'Core'], duration: '48–56 min', warmup: ['5–7 min de bike leve', 'Agachamentos para banco sem carga', '1 série leve de leg press'], finish: 'Caminhada leve e mobilidade confortável de quadril.', safety: 'A prioridade é manter joelhos e pés alinhados em cada repetição.',
      exercises: [ex('leg-press', 3, '8–12', 120, 'Pés firmes e joelhos acompanham os pés.'), ex('hip-thrust', 3, '8–12', 90, 'Contraia glúteos sem arquear a lombar.'), ex('leg-extension', 2, '10–15', 75, 'Amplitude confortável e controlada.'), ex('hip-abduction', 2, '12–15', 60, 'Não deixe a carga bater.'), ex('dead-bug', 3, '8–10/lado', 45, 'Lombar fica estável no chão.')],
    },
    {
      id: 'leticia-upper-a', person: 'leticia', title: 'Parte de cima', label: 'Costas + peito', objective: 'Fortalecer o corpo todo sem deixar braços e ombros de fora.',
      muscleGroups: ['Costas', 'Peito', 'Ombros', 'Bíceps', 'Tríceps'], duration: '48–56 min', warmup: ['5 min de elíptico leve', 'Mobilidade suave de ombros', '1 série de adaptação nas primeiras máquinas'], finish: 'Reduza o ritmo e faça respiração tranquila por 2–3 min.', safety: 'Mantenha a carga leve o suficiente para falar frases curtas durante as pausas.',
      exercises: [ex('lat-pulldown', 3, '8–12', 90, 'Barra na frente do corpo e peito alto.'), ex('chest-press', 3, '8–12', 90, 'Empurre sem elevar os ombros.'), ex('cable-row', 2, '10–12', 75, 'Sem balançar o tronco.'), ex('shoulder-press', 2, '10–12', 75, 'Mantenha as costas apoiadas.'), ex('cable-curl', 2, '10–12', 60, 'Cotovelos estáveis.'), ex('triceps-pushdown', 2, '10–12', 60, 'Controle a volta da corda.')],
    },
    {
      id: 'leticia-lower-b', person: 'leticia', title: 'Posterior & glúteos', label: 'Posterior + glúteos', objective: 'Trabalhar a cadeia posterior com boa amplitude e controle.',
      muscleGroups: ['Posterior', 'Glúteos', 'Quadríceps', 'Panturrilhas', 'Core'], duration: '50–58 min', warmup: ['5–7 min de caminhada leve', 'Dobradiça do quadril sem carga', '1 série leve de flexora e hip thrust'], finish: 'Caminhe até a respiração acalmar e alongue sem insistir na dor.', safety: 'No romeno, desça somente enquanto consegue manter coluna longa.',
      exercises: [ex('romanian-deadlift', 3, '8–12', 120, 'Quadril recua, halteres ficam próximos.'), ex('leg-curl', 3, '10–12', 90, 'Pausa curta na flexão.'), ex('hip-thrust', 3, '8–12', 90, 'Queixo levemente recolhido.'), ex('hack-squat', 2, '10–12', 90, 'Controle a descida na máquina.'), ex('calf-raise', 2, '12–15', 60, 'Suba sem girar os tornozelos.'), ex('plank', 3, '20–40 s', 45, 'Respire de forma contínua.')],
    },
    {
      id: 'leticia-full-body', person: 'leticia', title: 'Corpo todo & core', label: 'Full body', objective: 'Fechar a semana reforçando padrões básicos com volume moderado.',
      muscleGroups: ['Pernas', 'Glúteos', 'Peito', 'Costas', 'Ombros', 'Core'], duration: '48–56 min', warmup: ['5 min de bike ou caminhada', 'Agachamento sem carga e mobilidade leve', '1 série de adaptação no primeiro exercício'], finish: 'Caminhe devagar e escolha alongamentos leves se forem agradáveis.', safety: 'Este é um treino de consolidação: termine sentindo que poderia fazer mais uma repetição boa.',
      exercises: [ex('goblet-squat', 3, '10–12', 90, 'Use um banco como referência.'), ex('incline-press', 2, '10–12', 90, 'Punhos sobre os cotovelos.'), ex('lat-pulldown', 2, '10–12', 90, 'Puxe com os cotovelos.'), ex('hip-abduction', 2, '12–15', 60, 'Segure a abertura.'), ex('face-pull', 2, '12–15', 60, 'Movimento leve e preciso.'), ex('pallof-press', 2, '10/lado', 45, 'Quadril permanece alinhado.')],
    },
  ],
};

export const personMeta: Record<Person, { name: string; shortName: string; pronoun: string; accent: 'lime' | 'coral'; focus: string; avatar: string }> = {
  breno: { name: 'Breno', shortName: 'BR', pronoun: 'seu', accent: 'lime', focus: 'Força geral com atenção para peito, costas, braços e pernas.', avatar: 'B' },
  leticia: { name: 'Letícia', shortName: 'LE', pronoun: 'seu', accent: 'coral', focus: 'Corpo todo com prioridade para pernas, glúteos, posterior e core.', avatar: 'L' },
};

export const weekdayFromDate = (date: Date): Weekday => {
  const values: Weekday[] = ['dom', 'seg', 'ter', 'qua', 'qui', 'sex', 'sab'];
  return values[date.getDay()];
};

export const formatDate = (date: Date): string => new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short' }).format(date).replace('.', '');

export const formatFullDate = (date: Date): string => new Intl.DateTimeFormat('pt-BR', { weekday: 'long', day: '2-digit', month: 'long' }).format(date);
