import type { CardioOption, Exercise, ExerciseGif, ExerciseMedia, ExerciseTeaching, Person, Weekday, WorkoutDay, WorkoutExercise } from './types';

export const dayLabels: Record<Weekday, string> = {
  seg: 'Seg',
  ter: 'Ter',
  qua: 'Qua',
  qui: 'Qui',
  sex: 'Sex',
  sab: 'Sáb',
  dom: 'Dom',
};

export const dayNames: Record<Weekday, string> = {
  seg: 'segunda-feira',
  ter: 'terça-feira',
  qua: 'quarta-feira',
  qui: 'quinta-feira',
  sex: 'sexta-feira',
  sab: 'sábado',
  dom: 'domingo',
};

const aceLibrary = 'https://www.acefitness.org/resources/everyone/exercise-library/';

export const exerciseCatalog: Record<string, Exercise> = {
  'chest-press': {
    id: 'chest-press', name: 'Chest press na máquina', category: 'Peito', primary: 'Peitoral maior',
    secondary: ['Tríceps', 'Deltoide anterior'], equipment: 'Máquina de peito', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Ajuste o banco para que as alças fiquem na linha do meio do peito. Mantenha costas e cabeça apoiadas, pés firmes no chão.',
    execution: ['Segure as alças com os punhos alinhados aos antebraços.', 'Empurre para frente sem travar os cotovelos.', 'Retorne devagar até sentir alongar o peito, sem deixar a carga bater.'],
    breathing: 'Solte o ar ao empurrar e inspire ao voltar.',
    commonMistakes: ['Elevar os ombros em direção às orelhas', 'Desencostar as costas do banco', 'Usar impulso para fechar a repetição'],
    beginnersTips: ['Comece com a menor carga que permita controlar as duas fases.', 'Peça ajuda para ajustar banco e amplitude.'],
    easierAlternative: 'Flexão inclinada apoiando as mãos em um banco firme.', easierId: 'incline-push-up', substitutes: ['dumbbell-bench-press', 'incline-press', 'incline-push-up', 'cable-chest-fly'],
  },
  'cable-row': {
    id: 'cable-row', name: 'Remada sentada no cabo', category: 'Costas', primary: 'Latíssimo do dorso',
    secondary: ['Romboides', 'Bíceps', 'Deltoide posterior'], equipment: 'Cabo com triângulo', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Sente-se com joelhos levemente flexionados, peito aberto e coluna neutra. Segure o triângulo com os braços estendidos.',
    execution: ['Puxe as alças em direção ao umbigo conduzindo pelos cotovelos.', 'Pause quando as escápulas se aproximarem.', 'Estenda os braços controlando o retorno, sem arredondar a lombar.'],
    breathing: 'Expire na puxada e inspire na volta.',
    commonMistakes: ['Balançar o tronco para criar impulso', 'Encolher os ombros', 'Deixar o joelho travado'],
    beginnersTips: ['Imagine que os cotovelos vão para trás, não as mãos.', 'Use uma carga que permita pausar no final.'],
    easierAlternative: 'Remada com elástico preso em um ponto estável.', easierId: 'band-row', substitutes: ['chest-supported-row', 'one-arm-dumbbell-row', 'band-row'],
  },
  'lat-pulldown': {
    id: 'lat-pulldown', name: 'Puxada frontal', category: 'Costas', primary: 'Latíssimo do dorso',
    secondary: ['Bíceps', 'Romboides'], equipment: 'Polia alta', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Ajuste o apoio das coxas. Sente-se alto, peito aberto e mãos um pouco além da largura dos ombros.',
    execution: ['Puxe a barra em direção à parte alta do peito.', 'Mantenha cotovelos apontando para baixo e não atrás do corpo.', 'Suba a barra lentamente até quase estender os braços.'],
    breathing: 'Expire ao puxar e inspire ao subir.',
    commonMistakes: ['Puxar a barra atrás da nuca', 'Inclinar muito o tronco', 'Soltar a carga rapidamente'],
    beginnersTips: ['Pense em colocar os cotovelos nos bolsos.', 'A amplitude confortável é melhor que uma carga alta.'],
    easierAlternative: 'Puxada com elástico em pé.', easierId: 'band-lat-pulldown', substitutes: ['assisted-pullup', 'band-lat-pulldown'],
  },
  'shoulder-press': {
    id: 'shoulder-press', name: 'Desenvolvimento na máquina', category: 'Ombros', primary: 'Deltoides',
    secondary: ['Tríceps', 'Peitoral superior'], equipment: 'Máquina de ombros', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Encoste costas e cabeça. Posicione as alças um pouco abaixo da altura dos ombros, com punhos neutros.',
    execution: ['Empurre as alças para cima em uma linha confortável.', 'Pare antes de travar os cotovelos.', 'Desça até as alças ficarem próximas aos ombros.'],
    breathing: 'Expire na subida e inspire na descida.',
    commonMistakes: ['Arquear excessivamente a lombar', 'Baixar além da amplitude confortável', 'Impulsionar com as pernas'],
    beginnersTips: ['Mantenha as costelas para baixo e o abdômen levemente ativo.', 'Ajuste o banco antes de escolher a carga.'],
    easierAlternative: 'Desenvolvimento com halteres leves e encosto.', easierId: 'dumbbell-shoulder-press', substitutes: ['dumbbell-shoulder-press', 'band-shoulder-press'],
  },
  'triceps-pushdown': {
    id: 'triceps-pushdown', name: 'Tríceps na polia', category: 'Braços', primary: 'Tríceps braquial',
    secondary: ['Core'], equipment: 'Polia alta com corda', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique em pé com joelhos destravados, cotovelos próximos ao corpo e ombros relaxados.',
    execution: ['Empurre a corda até quase estender os cotovelos.', 'Separe levemente as pontas no final.', 'Volte só até o antebraço ficar perto da vertical, sem mover os cotovelos.'],
    breathing: 'Expire ao empurrar e inspire ao voltar.',
    commonMistakes: ['Abrir os cotovelos', 'Inclinar o tronco para usar o peso', 'Mover os ombros'],
    beginnersTips: ['Use uma carga que permita manter os cotovelos quietos.', 'Controle especialmente o retorno.'],
    easierAlternative: 'Tríceps com elástico leve.', easierId: 'band-triceps-extension', substitutes: ['overhead-triceps', 'band-triceps-extension', 'dumbbell-triceps-kickback'],
  },
  'dead-bug': {
    id: 'dead-bug', name: 'Dead bug', category: 'Core', primary: 'Abdômen profundo',
    secondary: ['Flexores do quadril', 'Oblíquos'], equipment: 'Colchonete', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Deite de costas, quadris e joelhos a 90 graus, braços apontando para o teto. Mantenha a lombar suave contra o chão.',
    execution: ['Estenda lentamente uma perna e o braço oposto.', 'Pare antes de perder o contato da lombar com o chão.', 'Volte ao centro e alterne os lados.'],
    breathing: 'Expire ao estender e inspire ao retornar.',
    commonMistakes: ['Deixar a lombar arquear', 'Acelerar a troca dos lados', 'Prender a respiração'],
    beginnersTips: ['Faça apenas o movimento das pernas se for mais fácil.', 'Diminua a amplitude antes de perder o controle.'],
    easierAlternative: 'Marcha deitada, movendo uma perna por vez.', easierId: 'heel-tap', substitutes: ['heel-tap', 'bird-dog', 'pallof-press'],
  },
  'leg-press': {
    id: 'leg-press', name: 'Leg press 45°', category: 'Pernas', primary: 'Quadríceps',
    secondary: ['Glúteos', 'Posterior de coxa'], equipment: 'Leg press', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Sente-se com quadril e costas apoiados. Pés na largura dos ombros, no meio da plataforma. Libere a trava apenas com controle.',
    execution: ['Desça a plataforma flexionando joelhos e quadris.', 'Pare quando a lombar começar a perder o apoio.', 'Empurre pelo meio do pé e volte sem travar os joelhos.'],
    breathing: 'Inspire na descida e expire ao empurrar.',
    commonMistakes: ['Deixar os joelhos colapsarem para dentro', 'Descer além do controle', 'Travar os joelhos no topo'],
    beginnersTips: ['Faça algumas repetições sem carga para sentir o percurso.', 'Mantenha o mesmo caminho dos joelhos durante todo o movimento.'],
    easierAlternative: 'Agachamento para um banco alto.', easierId: 'box-squat', substitutes: ['hack-squat', 'goblet-squat', 'box-squat', 'step-up'],
  },
  'leg-curl': {
    id: 'leg-curl', name: 'Flexora sentada', category: 'Pernas', primary: 'Posterior de coxa',
    secondary: ['Gastrocnêmio'], equipment: 'Cadeira flexora', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Ajuste o eixo da máquina ao seu joelho e apoie as costas. A almofada deve repousar logo acima do tornozelo.',
    execution: ['Flexione os joelhos levando a almofada para baixo.', 'Faça uma pausa curta sem tirar o quadril do banco.', 'Retorne de maneira lenta até quase estender os joelhos.'],
    breathing: 'Expire ao flexionar e inspire ao retornar.',
    commonMistakes: ['Levantar o quadril do assento', 'Chutar a almofada', 'Usar amplitude que cause dor no joelho'],
    beginnersTips: ['Ajuste a máquina antes de aumentar a carga.', 'Conte dois segundos na volta.'],
    easierAlternative: 'Flexão de joelho com bola ou toalha no chão.', substitutes: ['romanian-deadlift', 'stability-ball-curl', 'cable-pull-through'],
  },
  'goblet-squat': {
    id: 'goblet-squat', name: 'Agachamento com halter', category: 'Pernas', primary: 'Quadríceps',
    secondary: ['Glúteos', 'Core'], equipment: 'Halter', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Segure um halter junto ao peito, pés confortáveis e peito aberto. Pense em apoiar o peso no meio dos pés.',
    execution: ['Leve quadril para trás e flexione os joelhos.', 'Desça apenas enquanto mantiver o tronco e os pés estáveis.', 'Empurre o chão para voltar, mantendo joelhos alinhados aos pés.'],
    breathing: 'Inspire na descida e expire ao subir.',
    commonMistakes: ['Juntar os joelhos', 'Tirar os calcanhares do chão', 'Descer rápido demais'],
    beginnersTips: ['Use um banco como referência de profundidade.', 'Comece sem peso se ainda estiver aprendendo o caminho.'],
    easierAlternative: 'Agachamento no banco sem carga.', easierId: 'box-squat', substitutes: ['leg-press', 'hack-squat', 'box-squat', 'step-up'],
  },
  'hip-thrust': {
    id: 'hip-thrust', name: 'Elevação de quadril na máquina', category: 'Glúteos', primary: 'Glúteo máximo',
    secondary: ['Posterior de coxa', 'Core'], equipment: 'Máquina de hip thrust', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Apoie a lombar no encosto ou banco indicado, queixo levemente recolhido e pés afastados na largura do quadril.',
    execution: ['Empurre o chão com os pés e eleve o quadril.', 'Finalize com o corpo alinhado, contraindo glúteos sem arquear a lombar.', 'Desça controlando até o quadril quase tocar o apoio.'],
    breathing: 'Expire na subida e inspire na descida.',
    commonMistakes: ['Compensar com a lombar', 'Abrir demais as costelas', 'Colocar os pés longe demais'],
    beginnersTips: ['Pratique primeiro sem carga.', 'No topo, pense em aproximar o púbis do umbigo.'],
    easierAlternative: 'Elevação de quadril no chão.', easierId: 'glute-bridge', substitutes: ['glute-bridge', 'cable-pull-through', 'romanian-deadlift'],
  },
  'calf-raise': {
    id: 'calf-raise', name: 'Elevação de panturrilha', category: 'Pernas', primary: 'Gastrocnêmio',
    secondary: ['Sóleo'], equipment: 'Máquina ou degrau', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique estável com o antepé apoiado e calcanhares livres, segurando em algo firme quando necessário.',
    execution: ['Eleve os calcanhares até o máximo confortável.', 'Pause brevemente no alto.', 'Desça devagar sentindo alongar a panturrilha.'],
    breathing: 'Respire de forma contínua, expirando na subida.',
    commonMistakes: ['Fazer movimentos curtos e rápidos', 'Perder a estabilidade do tornozelo', 'Usar impulso'],
    beginnersTips: ['Priorize amplitude e controle.', 'Comece segurando em um apoio.'],
    easierAlternative: 'Elevação de panturrilha sentado sem carga.', easierId: 'seated-calf-raise', substitutes: ['single-leg-calf-raise', 'seated-calf-raise'],
  },
  'plank': {
    id: 'plank', name: 'Prancha frontal', category: 'Core', primary: 'Abdômen',
    secondary: ['Glúteos', 'Ombros'], equipment: 'Colchonete', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Apoie antebraços e joelhos ou pés. Cotovelos ficam abaixo dos ombros, pescoço alinhado.',
    execution: ['Contraia abdômen e glúteos.', 'Mantenha uma linha confortável dos ombros ao quadril.', 'Pare antes de a lombar ceder ou a respiração travar.'],
    breathing: 'Respire devagar e continuamente, sem prender o ar.',
    commonMistakes: ['Deixar o quadril cair', 'Empurrar o chão com os ombros encolhidos', 'Segurar a respiração'],
    beginnersTips: ['Comece com os joelhos apoiados.', 'É melhor sustentar 20 segundos com qualidade do que forçar 60.'],
    easierAlternative: 'Prancha com joelhos no chão.', substitutes: ['dead-bug', 'bird-dog', 'pallof-press'],
  },
  'incline-press': {
    id: 'incline-press', name: 'Supino inclinado com halteres', category: 'Peito', primary: 'Peitoral superior',
    secondary: ['Tríceps', 'Deltoide anterior'], equipment: 'Banco inclinado + halteres', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Banco em inclinação moderada, pés no chão e halteres na altura do peito. Escápulas apoiadas e ombros longe das orelhas.',
    execution: ['Empurre os halteres para cima mantendo punhos sobre os cotovelos.', 'Aproxime sem bater os halteres.', 'Desça com cotovelos em um ângulo confortável, sem perder o apoio.'],
    breathing: 'Expire na subida e inspire na descida.',
    commonMistakes: ['Abrir os cotovelos em 90 graus', 'Descer rápido', 'Usar halteres difíceis de posicionar'],
    beginnersTips: ['Peça ajuda para colocar os halteres no lugar.', 'Comece com pouca carga para dominar a trajetória.'],
    easierAlternative: 'Chest press na máquina.', easierId: 'chest-press', substitutes: ['chest-press', 'dumbbell-bench-press', 'incline-push-up'],
  },
  'face-pull': {
    id: 'face-pull', name: 'Face pull', category: 'Ombros', primary: 'Deltoide posterior',
    secondary: ['Romboides', 'Manguito rotador'], equipment: 'Cabo com corda', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Polia na altura do rosto, postura alta, braços estendidos e corda segura com polegares apontando para trás.',
    execution: ['Puxe a corda na direção do rosto, abrindo as mãos.', 'Pense em girar os braços sem elevar os ombros.', 'Retorne lentamente mantendo o tronco parado.'],
    breathing: 'Expire na puxada e inspire na volta.',
    commonMistakes: ['Usar uma carga alta', 'Inclinar o corpo para trás', 'Forçar a amplitude do ombro'],
    beginnersTips: ['Faça leve e com pausa.', 'O movimento é para sentir a parte posterior do ombro e as costas altas.'],
    easierAlternative: 'Abertura reversa com elástico leve.', easierId: 'band-face-pull', substitutes: ['band-face-pull', 'reverse-fly', 'cable-row'],
  },
  'dumbbell-curl': {
    id: 'dumbbell-curl', name: 'Rosca alternada', category: 'Braços', primary: 'Bíceps',
    secondary: ['Braquial', 'Antebraço'], equipment: 'Halteres', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique em pé com halteres ao lado do corpo, palmas voltadas para frente e cotovelos próximos ao tronco.',
    execution: ['Flexione um cotovelo sem mover o ombro.', 'Suba até perto do peito sem perder o punho neutro.', 'Desça devagar antes de trocar o lado.'],
    breathing: 'Expire na subida e inspire na descida.',
    commonMistakes: ['Balançar o tronco', 'Projetar o cotovelo para frente', 'Descer sem controle'],
    beginnersTips: ['Imagine que o cotovelo está preso ao corpo.', 'Alterne os lados para focar na técnica.'],
    easierAlternative: 'Rosca com elástico leve.', easierId: 'band-curl', substitutes: ['cable-curl', 'hammer-curl', 'band-curl'],
  },
  'overhead-triceps': {
    id: 'overhead-triceps', name: 'Tríceps acima da cabeça', category: 'Braços', primary: 'Tríceps braquial',
    secondary: ['Core'], equipment: 'Cabo ou halter', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique sentado ou em pé, braços acima da cabeça e cotovelos apontando para frente, sem abrir demais.',
    execution: ['Flexione os cotovelos levando as mãos atrás da cabeça.', 'Mantenha os braços relativamente parados.', 'Estenda sem travar e volte devagar.'],
    breathing: 'Expire ao estender e inspire ao flexionar.',
    commonMistakes: ['Abrir muito os cotovelos', 'Arquear a lombar', 'Forçar a amplitude do ombro'],
    beginnersTips: ['Escolha o cabo se tiver dificuldade para posicionar um halter.', 'Use uma carga bem menor que no pushdown.'],
    easierAlternative: 'Tríceps na polia com corda.', easierId: 'triceps-pushdown', substitutes: ['triceps-pushdown', 'band-triceps-extension', 'dumbbell-triceps-kickback'],
  },
  'pallof-press': {
    id: 'pallof-press', name: 'Pallof press', category: 'Core', primary: 'Core anti-rotação',
    secondary: ['Oblíquos', 'Ombros'], equipment: 'Cabo ou elástico', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique de lado para a polia, pés afastados e mãos junto ao peito. Ajuste a distância para sentir uma tensão moderada.',
    execution: ['Empurre as mãos para longe do peito.', 'Resista à rotação do tronco e mantenha quadril alinhado.', 'Traga as mãos de volta sem perder a postura.'],
    breathing: 'Expire ao estender e inspire ao retornar.',
    commonMistakes: ['Girar o tronco em direção ao cabo', 'Usar impulso', 'Travar os joelhos'],
    beginnersTips: ['Comece com pouca carga e tempo de pausa curto.', 'Reduza a distância da polia se perder o alinhamento.'],
    easierAlternative: 'Pallof press com elástico leve.', easierId: 'band-pallof-press', substitutes: ['band-pallof-press', 'dead-bug', 'bird-dog', 'plank'],
  },
  'romanian-deadlift': {
    id: 'romanian-deadlift', name: 'Levantamento romeno com halteres', category: 'Posterior', primary: 'Posterior de coxa',
    secondary: ['Glúteos', 'Lombar'], equipment: 'Halteres', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Pés na largura do quadril, halteres à frente das coxas, costas longas e joelhos levemente destravados.',
    execution: ['Leve o quadril para trás mantendo os halteres próximos às pernas.', 'Desça só até sentir tensão no posterior sem arredondar a coluna.', 'Empurre o chão e estenda o quadril para voltar.'],
    breathing: 'Inspire ao descer e expire ao subir.',
    commonMistakes: ['Agachar em vez de fazer a dobradiça do quadril', 'Afastar os halteres das pernas', 'Arredondar a lombar'],
    beginnersTips: ['Pratique a dobradiça com um cabo de vassoura nas costas.', 'Pare antes de a mobilidade limitar a postura.'],
    easierAlternative: 'Dobradiça do quadril sem carga.', easierId: 'bodyweight-hip-hinge', substitutes: ['leg-curl', 'cable-pull-through', 'hip-thrust'],
  },
  'leg-extension': {
    id: 'leg-extension', name: 'Cadeira extensora', category: 'Pernas', primary: 'Quadríceps',
    secondary: ['Core'], equipment: 'Cadeira extensora', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Ajuste o eixo ao joelho e o rolo na frente do tornozelo. Sente-se com lombar apoiada e joelhos alinhados.',
    execution: ['Estenda os joelhos até uma posição confortável.', 'Pause brevemente sem travar.', 'Desça com controle até o início.'],
    breathing: 'Expire na extensão e inspire ao retornar.',
    commonMistakes: ['Chutar a carga', 'Desencostar o quadril', 'Travar o joelho com força'],
    beginnersTips: ['Faça uma amplitude sem dor.', 'Ajuste o rolo para não pressionar a canela.'],
    easierAlternative: 'Extensão de joelho sentado sem carga.', substitutes: ['leg-press', 'goblet-squat', 'box-squat'],
  },
  'hip-abduction': {
    id: 'hip-abduction', name: 'Abdutora na máquina', category: 'Glúteos', primary: 'Glúteo médio',
    secondary: ['Glúteo máximo', 'Abdutores do quadril'], equipment: 'Máquina abdutora', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Sente-se com costas apoiadas, pés nos apoios e joelhos alinhados com o eixo indicado pela máquina.',
    execution: ['Abra as pernas contra a resistência sem inclinar o tronco.', 'Pause na abertura confortável.', 'Retorne devagar sem deixar as placas baterem.'],
    breathing: 'Expire ao abrir e inspire ao voltar.',
    commonMistakes: ['Usar balanço do tronco', 'Abrir além da mobilidade', 'Soltar a volta'],
    beginnersTips: ['Comece com uma carga que permita segurar a abertura.', 'A qualidade da volta importa tanto quanto a abertura.'],
    easierAlternative: 'Abdução deitado de lado.', easierId: 'side-lying-leg-raise', substitutes: ['side-lying-leg-raise', 'band-abduction'],
  },
  'assisted-pullup': {
    id: 'assisted-pullup', name: 'Puxada na máquina assistida', category: 'Costas', primary: 'Latíssimo do dorso',
    secondary: ['Bíceps', 'Core'], equipment: 'Máquina de barra assistida', difficulty: 'Intermediário', sourceUrl: aceLibrary,
    startingPosture: 'Apoie os joelhos, segure as barras e mantenha o peito alto. Escolha assistência suficiente para controlar o movimento.',
    execution: ['Puxe o corpo levando o peito em direção às mãos.', 'Evite encolher os ombros e pause no alto.', 'Desça até quase estender os cotovelos, sem despencar.'],
    breathing: 'Expire na subida e inspire na descida.',
    commonMistakes: ['Balançar o corpo', 'Projetar o queixo para alcançar a barra', 'Descer sem controle'],
    beginnersTips: ['Prefira mais assistência e amplitude completa.', 'Peça instrução para entrar e sair da máquina com segurança.'],
    easierAlternative: 'Puxada frontal na polia.', easierId: 'lat-pulldown', substitutes: ['lat-pulldown', 'band-lat-pulldown'],
  },
  'cable-curl': {
    id: 'cable-curl', name: 'Rosca na polia', category: 'Braços', primary: 'Bíceps',
    secondary: ['Braquial', 'Antebraço'], equipment: 'Polia baixa + barra curta', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique estável, segurando a barra com palmas para cima e cotovelos próximos ao corpo.',
    execution: ['Flexione os cotovelos sem mover os ombros.', 'Aproxime a barra do peito dentro da amplitude confortável.', 'Retorne devagar mantendo tensão no cabo.'],
    breathing: 'Expire na subida e inspire na volta.',
    commonMistakes: ['Inclinar o tronco para trás', 'Estender completamente de forma brusca', 'Usar o quadril'],
    beginnersTips: ['Fique perto da polia para não ser puxado.', 'Use o cabo para aprender a controlar a volta.'],
    easierAlternative: 'Rosca alternada com halter leve.', easierId: 'dumbbell-curl', substitutes: ['dumbbell-curl', 'hammer-curl', 'band-curl'],
  },
  'chest-supported-row': {
    id: 'chest-supported-row', name: 'Remada com peito apoiado', category: 'Costas', primary: 'Romboides',
    secondary: ['Latíssimo do dorso', 'Bíceps'], equipment: 'Banco inclinado + halteres', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Deite com o peito apoiado no banco inclinado, pés firmes e halteres pendendo abaixo dos ombros.',
    execution: ['Puxe os halteres conduzindo pelos cotovelos.', 'Aproxime escápulas sem levantar o peito do banco.', 'Desça os pesos até quase estender os braços.'],
    breathing: 'Expire na puxada e inspire na descida.',
    commonMistakes: ['Levantar o tronco', 'Encolher os ombros', 'Bater os pesos no banco'],
    beginnersTips: ['O apoio ajuda a evitar balanço.', 'Escolha halteres leves para manter o peito encostado.'],
    easierAlternative: 'Remada sentada no cabo.', easierId: 'cable-row', substitutes: ['cable-row', 'one-arm-dumbbell-row', 'band-row'],
  },
  'hack-squat': {
    id: 'hack-squat', name: 'Agachamento no hack', category: 'Pernas', primary: 'Quadríceps',
    secondary: ['Glúteos', 'Posterior de coxa'], equipment: 'Máquina hack', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Apoie costas e ombros, pés na plataforma e joelhos apontando para a mesma direção dos pés.',
    execution: ['Desça flexionando joelhos e quadris sem tirar as costas do apoio.', 'Pare antes de perder a posição confortável.', 'Empurre a plataforma mantendo joelhos destravados.'],
    breathing: 'Inspire na descida e expire ao subir.',
    commonMistakes: ['Deixar os joelhos fecharem', 'Tirar os calcanhares do apoio', 'Travar os joelhos no final'],
    beginnersTips: ['Peça para alguém mostrar as travas da máquina.', 'Comece somente com o peso da máquina.'],
    easierAlternative: 'Leg press com pouca carga.', easierId: 'leg-press', substitutes: ['leg-press', 'goblet-squat', 'box-squat', 'step-up'],
  },
  'lateral-raise': {
    id: 'lateral-raise', name: 'Elevação lateral', category: 'Ombros', primary: 'Deltoide lateral',
    secondary: ['Trapézio superior', 'Core'], equipment: 'Halteres', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique em pé com halteres ao lado do corpo, braços levemente flexionados e ombros relaxados.',
    execution: ['Eleve os braços para os lados até a altura confortável dos ombros.', 'Mantenha mãos e cotovelos em uma linha suave.', 'Desça lentamente sem descansar a carga no corpo.'],
    breathing: 'Expire ao subir e inspire ao descer.',
    commonMistakes: ['Usar balanço', 'Elevar os ombros', 'Escolher carga alta demais'],
    beginnersTips: ['Halteres leves funcionam melhor.', 'Pare no ponto em que o ombro mantém espaço e controle.'],
    easierAlternative: 'Elevação lateral com elástico leve.', easierId: 'band-lateral-raise', substitutes: ['band-lateral-raise', 'cable-lateral-raise', 'face-pull'],
  },
  'dumbbell-bench-press': {
    id: 'dumbbell-bench-press', name: 'Supino reto com halteres', category: 'Peito', primary: 'Peitoral maior',
    secondary: ['Tríceps', 'Deltoide anterior'], equipment: 'Banco reto + halteres', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Deite no banco com os pés no chão e os halteres ao lado do peito. Mantenha escápulas apoiadas e punhos alinhados.',
    execution: ['Empurre os halteres para cima sem bater um no outro.', 'Desça com cotovelos em um ângulo confortável e controlado.', 'Mantenha o peito e a cabeça apoiados durante o movimento.'],
    breathing: 'Expire ao empurrar e inspire ao descer.',
    commonMistakes: ['Soltar os halteres rapidamente', 'Abrir demais os cotovelos', 'Tirar os pés do chão'],
    beginnersTips: ['Use halteres leves e peça ajuda para posicioná-los.', 'Pare a descida antes de perder o apoio dos ombros.'],
    easierAlternative: 'Flexão inclinada com as mãos em um banco firme.', easierId: 'incline-push-up', substitutes: ['chest-press', 'incline-press', 'incline-push-up'],
  },
  'incline-push-up': {
    id: 'incline-push-up', name: 'Flexão inclinada', category: 'Peito', primary: 'Peitoral maior',
    secondary: ['Tríceps', 'Ombros', 'Core'], equipment: 'Banco firme ou barra do rack', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Apoie as mãos um pouco além dos ombros em uma superfície estável. Estenda o corpo e mantenha abdômen ativo.',
    execution: ['Flexione os cotovelos levando o peito em direção ao apoio.', 'Mantenha o corpo em linha, sem deixar o quadril cair.', 'Empurre o apoio até voltar sem travar os cotovelos.'],
    breathing: 'Inspire ao descer e expire ao empurrar.',
    commonMistakes: ['Deixar os cotovelos abrirem demais', 'Perder o alinhamento do quadril', 'Usar uma superfície instável'],
    beginnersTips: ['Quanto mais alto o apoio, mais fácil fica.', 'Afaste os pés para aumentar a estabilidade.'],
    easierAlternative: 'Flexão contra a parede.', substitutes: ['chest-press', 'dumbbell-bench-press', 'cable-chest-fly'],
  },
  'cable-chest-fly': {
    id: 'cable-chest-fly', name: 'Crucifixo no cabo', category: 'Peito', primary: 'Peitoral maior',
    secondary: ['Deltoide anterior', 'Core'], equipment: 'Duas polias', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique entre as polias com um pé à frente, peito aberto e cotovelos levemente flexionados.',
    execution: ['Aproxime as mãos à frente do peito em um arco confortável.', 'Pause sem projetar os ombros para frente.', 'Abra os braços devagar mantendo a mesma flexão dos cotovelos.'],
    breathing: 'Expire ao aproximar as mãos e inspire ao abrir.',
    commonMistakes: ['Estender e travar os cotovelos', 'Usar balanço do tronco', 'Deixar os ombros subirem'],
    beginnersTips: ['Use pouca carga para controlar todo o arco.', 'Se as polias estiverem ocupadas, use uma das opções de supino.'],
    easierAlternative: 'Flexão inclinada.', easierId: 'incline-push-up', substitutes: ['chest-press', 'dumbbell-bench-press', 'incline-push-up'],
  },
  'one-arm-dumbbell-row': {
    id: 'one-arm-dumbbell-row', name: 'Remada unilateral com halter', category: 'Costas', primary: 'Latíssimo do dorso',
    secondary: ['Romboides', 'Bíceps'], equipment: 'Banco + halter', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Apoie uma mão e um joelho no banco, mantenha a coluna neutra e o halter pendendo abaixo do ombro.',
    execution: ['Puxe o halter em direção ao quadril conduzindo pelo cotovelo.', 'Pause sem girar o tronco.', 'Desça o peso devagar e repita antes de trocar o lado.'],
    breathing: 'Expire na puxada e inspire na descida.',
    commonMistakes: ['Girar o tronco para subir o peso', 'Encolher o ombro', 'Arredondar a lombar'],
    beginnersTips: ['Use o banco para tirar impulso.', 'Comece pelo lado mais fraco e iguale as repetições.'],
    easierAlternative: 'Remada com o peito apoiado.', easierId: 'chest-supported-row', substitutes: ['cable-row', 'chest-supported-row', 'band-row'],
  },
  'band-row': {
    id: 'band-row', name: 'Remada com elástico', category: 'Costas', primary: 'Romboides',
    secondary: ['Latíssimo do dorso', 'Bíceps'], equipment: 'Elástico preso em ponto estável', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Prenda o elástico na altura do peito, afaste os pés e mantenha o tronco alto com os braços estendidos.',
    execution: ['Puxe as mãos em direção às costelas.', 'Aproxime as escápulas sem elevar os ombros.', 'Retorne lentamente sem deixar o elástico puxar o corpo.'],
    breathing: 'Expire na puxada e inspire na volta.',
    commonMistakes: ['Prender o elástico em local inseguro', 'Balançar o tronco', 'Soltar a volta'],
    beginnersTips: ['A tensão deve permitir uma pausa no final.', 'É uma boa opção quando cabos e máquinas estão ocupados.'],
    easierAlternative: 'Remada sentada com elástico mais leve.', substitutes: ['cable-row', 'one-arm-dumbbell-row', 'chest-supported-row'],
  },
  'band-lat-pulldown': {
    id: 'band-lat-pulldown', name: 'Puxada com elástico', category: 'Costas', primary: 'Latíssimo do dorso',
    secondary: ['Bíceps', 'Romboides'], equipment: 'Elástico preso acima da cabeça', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Prenda o elástico acima da cabeça, ajoelhe ou fique em pé com peito aberto e braços estendidos.',
    execution: ['Puxe as mãos para a parte alta do peito conduzindo pelos cotovelos.', 'Pause sem encolher os ombros.', 'Suba as mãos controlando a tensão.'],
    breathing: 'Expire ao puxar e inspire ao subir.',
    commonMistakes: ['Prender o elástico em local inseguro', 'Puxar atrás da nuca', 'Inclinar muito o tronco'],
    beginnersTips: ['Comece com elástico leve e amplitude confortável.', 'Mantenha o ponto de ancoragem acima e à frente do corpo.'],
    easierAlternative: 'Puxada frontal com assistência leve.', easierId: 'lat-pulldown', substitutes: ['lat-pulldown', 'assisted-pullup'],
  },
  'dumbbell-shoulder-press': {
    id: 'dumbbell-shoulder-press', name: 'Desenvolvimento com halteres', category: 'Ombros', primary: 'Deltoides',
    secondary: ['Tríceps', 'Core'], equipment: 'Banco + halteres', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Sente-se com costas apoiadas, halteres na altura dos ombros e punhos alinhados aos antebraços.',
    execution: ['Empurre os halteres para cima em uma linha confortável.', 'Pare antes de travar os cotovelos.', 'Desça devagar até a altura dos ombros.'],
    breathing: 'Expire na subida e inspire na descida.',
    commonMistakes: ['Arquear a lombar', 'Bater os halteres no alto', 'Escolher carga que exija impulso'],
    beginnersTips: ['Use encosto e halteres leves.', 'Se sentir desconforto, reduza a amplitude e peça orientação.'],
    easierAlternative: 'Desenvolvimento na máquina com pouca carga.', easierId: 'shoulder-press', substitutes: ['shoulder-press', 'band-shoulder-press'],
  },
  'band-shoulder-press': {
    id: 'band-shoulder-press', name: 'Desenvolvimento com elástico', category: 'Ombros', primary: 'Deltoides',
    secondary: ['Tríceps', 'Core'], equipment: 'Elástico', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Pise no centro do elástico ou prenda-o abaixo, mãos na altura dos ombros e tronco alto.',
    execution: ['Empurre as mãos para cima sem arquear a lombar.', 'Pare antes de travar os cotovelos.', 'Desça devagar mantendo a tensão do elástico.'],
    breathing: 'Expire na subida e inspire na descida.',
    commonMistakes: ['Usar impulso das pernas', 'Arquear a lombar', 'Prender o elástico em local inseguro'],
    beginnersTips: ['Use resistência leve e amplitude confortável.', 'Sente-se em um banco se precisar de mais estabilidade.'],
    easierAlternative: 'Desenvolvimento na máquina com pouca carga.', easierId: 'shoulder-press', substitutes: ['shoulder-press', 'dumbbell-shoulder-press'],
  },
  'band-triceps-extension': {
    id: 'band-triceps-extension', name: 'Tríceps com elástico', category: 'Braços', primary: 'Tríceps braquial',
    secondary: ['Core'], equipment: 'Elástico preso acima', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique de frente para o ponto de ancoragem, cotovelos próximos ao corpo e mãos segurando o elástico.',
    execution: ['Estenda os cotovelos levando as mãos para baixo.', 'Mantenha os ombros relaxados e os cotovelos parados.', 'Retorne com controle até o antebraço ficar próximo da vertical.'],
    breathing: 'Expire ao estender e inspire ao retornar.',
    commonMistakes: ['Abrir os cotovelos', 'Usar o peso do corpo', 'Ancorar o elástico em local inseguro'],
    beginnersTips: ['Deixe o elástico com tensão leve no início.', 'É uma troca prática para quando a polia estiver ocupada.'],
    easierAlternative: 'Extensão sem elástico, praticando o caminho dos cotovelos.', substitutes: ['triceps-pushdown', 'overhead-triceps', 'dumbbell-triceps-kickback'],
  },
  'dumbbell-triceps-kickback': {
    id: 'dumbbell-triceps-kickback', name: 'Tríceps coice com halteres', category: 'Braços', primary: 'Tríceps braquial',
    secondary: ['Core', 'Deltoide posterior'], equipment: 'Halteres', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Incline o tronco com coluna neutra, cotovelos junto ao corpo e braços dobrados.',
    execution: ['Estenda os cotovelos levando os halteres para trás.', 'Pause sem girar os ombros.', 'Dobre os cotovelos lentamente para retornar.'],
    breathing: 'Expire ao estender e inspire ao voltar.',
    commonMistakes: ['Balançar os braços', 'Arredondar a lombar', 'Usar halteres pesados demais'],
    beginnersTips: ['Apoie uma mão em um banco para ficar estável.', 'Use carga baixa e foque na contração do tríceps.'],
    easierAlternative: 'Tríceps com elástico leve.', easierId: 'band-triceps-extension', substitutes: ['triceps-pushdown', 'overhead-triceps', 'band-triceps-extension'],
  },
  'hammer-curl': {
    id: 'hammer-curl', name: 'Rosca martelo', category: 'Braços', primary: 'Braquial e bíceps',
    secondary: ['Braquiorradial', 'Antebraço'], equipment: 'Halteres', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique em pé com palmas voltadas uma para a outra, braços ao lado do corpo e cotovelos quietos.',
    execution: ['Flexione um cotovelo mantendo a palma em posição neutra.', 'Suba sem projetar o ombro para frente.', 'Desça lentamente e alterne os lados.'],
    breathing: 'Expire na subida e inspire na descida.',
    commonMistakes: ['Balançar o corpo', 'Mover os cotovelos', 'Soltar o halter na descida'],
    beginnersTips: ['Use carga que permita manter os punhos retos.', 'Pode ser feito com os dois braços ou alternado.'],
    easierAlternative: 'Rosca com elástico leve.', easierId: 'band-curl', substitutes: ['dumbbell-curl', 'cable-curl', 'band-curl'],
  },
  'band-curl': {
    id: 'band-curl', name: 'Rosca com elástico', category: 'Braços', primary: 'Bíceps',
    secondary: ['Braquial', 'Antebraço'], equipment: 'Elástico', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Pise no centro do elástico, fique alto e mantenha cotovelos junto ao tronco.',
    execution: ['Flexione os cotovelos levando as mãos em direção aos ombros.', 'Pause sem elevar os ombros.', 'Desça devagar mantendo alguma tensão no elástico.'],
    breathing: 'Expire na subida e inspire na volta.',
    commonMistakes: ['Balançar o tronco', 'Soltar o elástico', 'Deixar os cotovelos avançarem'],
    beginnersTips: ['Use um elástico de resistência confortável.', 'Reduza a amplitude se perder o controle.'],
    easierAlternative: 'Rosca alternada com halteres leves.', easierId: 'dumbbell-curl', substitutes: ['dumbbell-curl', 'cable-curl', 'hammer-curl'],
  },
  'box-squat': {
    id: 'box-squat', name: 'Agachamento para o banco', category: 'Pernas', primary: 'Quadríceps',
    secondary: ['Glúteos', 'Core'], equipment: 'Banco ou caixa firme', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique à frente de um banco firme, pés confortáveis e peito aberto. O banco serve apenas como referência.',
    execution: ['Leve o quadril para trás e flexione os joelhos.', 'Toque o banco com controle sem despencar ou relaxar.', 'Empurre o chão para voltar mantendo joelhos alinhados aos pés.'],
    breathing: 'Inspire ao descer e expire ao subir.',
    commonMistakes: ['Sentar e relaxar no banco', 'Deixar os joelhos fecharem', 'Tirar os calcanhares do chão'],
    beginnersTips: ['Escolha um banco alto no início.', 'Faça sem carga até dominar o caminho.'],
    easierAlternative: 'Sentar e levantar de uma cadeira alta.', substitutes: ['leg-press', 'goblet-squat', 'hack-squat', 'step-up'],
  },
  'step-up': {
    id: 'step-up', name: 'Subida no banco', category: 'Pernas', primary: 'Quadríceps e glúteos',
    secondary: ['Posterior de coxa', 'Panturrilhas', 'Core'], equipment: 'Banco baixo e firme', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique diante de um banco baixo e firme, olhando para frente e com os pés paralelos.',
    execution: ['Apoie um pé inteiro no banco e empurre o chão com esse pé.', 'Suba sem saltar e mantenha o joelho alinhado.', 'Desça devagar e repita antes de trocar o lado.'],
    breathing: 'Expire ao subir e inspire ao descer.',
    commonMistakes: ['Usar impulso da perna de trás', 'Escolher banco alto demais', 'Deixar o joelho cair para dentro'],
    beginnersTips: ['Comece com banco baixo e sem carga.', 'Segure em um apoio se precisar de equilíbrio.'],
    easierAlternative: 'Agachamento para banco.', easierId: 'box-squat', substitutes: ['box-squat', 'goblet-squat', 'reverse-lunge'],
  },
  'reverse-lunge': {
    id: 'reverse-lunge', name: 'Passada reversa', category: 'Pernas', primary: 'Glúteos e quadríceps',
    secondary: ['Posterior de coxa', 'Core'], equipment: 'Peso corporal ou halteres', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique alto com pés na largura do quadril e segure em um apoio se necessário.',
    execution: ['Dê um passo para trás e flexione os dois joelhos.', 'Desça apenas enquanto mantém o tronco estável.', 'Empurre o chão com o pé da frente para voltar.'],
    breathing: 'Inspire ao descer e expire ao subir.',
    commonMistakes: ['Perder o equilíbrio por dar passo curto', 'Deixar o joelho da frente colapsar', 'Acelerar a descida'],
    beginnersTips: ['Use apoio e faça amplitude pequena no começo.', 'Mantenha a maior parte do peso no meio do pé da frente.'],
    easierAlternative: 'Agachamento para banco.', easierId: 'box-squat', substitutes: ['box-squat', 'step-up', 'goblet-squat'],
  },
  'stability-ball-curl': {
    id: 'stability-ball-curl', name: 'Flexão de joelhos na bola', category: 'Posterior', primary: 'Posterior de coxa',
    secondary: ['Glúteos', 'Core'], equipment: 'Bola suíça ou toalha', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Deite de costas, calcanhares apoiados na bola e quadril confortável no chão. Mantenha abdômen ativo.',
    execution: ['Eleve o quadril até formar uma linha confortável.', 'Puxe a bola aproximando os calcanhares do corpo.', 'Estenda as pernas devagar sem deixar o quadril despencar.'],
    breathing: 'Expire ao puxar a bola e inspire ao estender.',
    commonMistakes: ['Arquear a lombar', 'Estender rápido demais', 'Usar bola instável ou inadequada'],
    beginnersTips: ['Comece com uma ponte estática e amplitude curta.', 'Use uma toalha no chão se não tiver bola.'],
    easierAlternative: 'Ponte de glúteos sem flexionar os joelhos.', easierId: 'glute-bridge', substitutes: ['leg-curl', 'romanian-deadlift', 'glute-bridge'],
  },
  'cable-pull-through': {
    id: 'cable-pull-through', name: 'Pull-through no cabo', category: 'Posterior', primary: 'Glúteos',
    secondary: ['Posterior de coxa', 'Core'], equipment: 'Polia baixa + corda', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique de costas para a polia, corda entre as pernas, pés firmes e joelhos levemente destravados.',
    execution: ['Leve o quadril para trás mantendo a coluna longa.', 'Empurre o chão e estenda o quadril para ficar alto.', 'Contraia os glúteos sem arquear a lombar e repita.'],
    breathing: 'Inspire ao recuar o quadril e expire ao subir.',
    commonMistakes: ['Agachar em vez de fazer a dobradiça', 'Arredondar as costas', 'Puxar com os braços'],
    beginnersTips: ['Use pouca carga e pratique a dobradiça sem cabo primeiro.', 'Mantenha a corda próxima ao corpo.'],
    easierAlternative: 'Dobradiça do quadril sem carga.', easierId: 'bodyweight-hip-hinge', substitutes: ['romanian-deadlift', 'hip-thrust', 'bodyweight-hip-hinge'],
  },
  'bodyweight-hip-hinge': {
    id: 'bodyweight-hip-hinge', name: 'Dobradiça do quadril sem carga', category: 'Posterior', primary: 'Posterior de coxa',
    secondary: ['Glúteos', 'Core'], equipment: 'Peso corporal', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique com pés na largura do quadril, mãos nas costelas e coluna longa.',
    execution: ['Leve o quadril para trás mantendo uma leve flexão dos joelhos.', 'Desça até sentir tensão confortável no posterior.', 'Empurre o chão e contraia os glúteos para voltar.'],
    breathing: 'Inspire ao recuar o quadril e expire ao voltar.',
    commonMistakes: ['Arredondar a lombar', 'Flexionar demais os joelhos', 'Descer além da mobilidade'],
    beginnersTips: ['Pratique perto de uma parede, levando o quadril até ela.', 'Use um cabo de vassoura nas costas como referência.'],
    easierAlternative: 'Dobradiça curta até a parede.', substitutes: ['romanian-deadlift', 'cable-pull-through', 'hip-thrust'],
  },
  'glute-bridge': {
    id: 'glute-bridge', name: 'Ponte de glúteos', category: 'Glúteos', primary: 'Glúteo máximo',
    secondary: ['Posterior de coxa', 'Core'], equipment: 'Colchonete', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Deite de costas com joelhos dobrados, pés no chão e braços ao lado do corpo.',
    execution: ['Pressione o chão com os pés e eleve o quadril.', 'Pare quando o corpo formar uma linha confortável dos ombros aos joelhos.', 'Desça devagar sem relaxar completamente o abdômen.'],
    breathing: 'Expire ao subir e inspire ao descer.',
    commonMistakes: ['Arquear a lombar no topo', 'Deixar os joelhos abrirem ou fecharem', 'Usar impulso'],
    beginnersTips: ['Faça uma pausa de um segundo no alto.', 'A amplitude termina antes de a lombar compensar.'],
    easierAlternative: 'Ponte curta sem elevar tanto o quadril.', substitutes: ['hip-thrust', 'cable-pull-through', 'romanian-deadlift'],
  },
  'side-lying-leg-raise': {
    id: 'side-lying-leg-raise', name: 'Abdução deitado de lado', category: 'Glúteos', primary: 'Glúteo médio',
    secondary: ['Abdutores do quadril', 'Core'], equipment: 'Colchonete', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Deite de lado com pernas estendidas ou joelhos levemente dobrados e quadril empilhado.',
    execution: ['Eleve a perna de cima sem girar o pé para fora.', 'Pause no ponto em que o quadril continua estável.', 'Desça lentamente sem deixar a perna despencar.'],
    breathing: 'Expire ao elevar e inspire ao descer.',
    commonMistakes: ['Girar o corpo para trás', 'Elevar além do controle', 'Fazer movimentos rápidos'],
    beginnersTips: ['Use amplitude menor e mantenha o pé apontado para frente.', 'Pode adicionar elástico apenas depois de dominar o movimento.'],
    easierAlternative: 'Abdução curta sem elástico.', substitutes: ['hip-abduction', 'band-abduction', 'glute-bridge'],
  },
  'band-abduction': {
    id: 'band-abduction', name: 'Abdução com elástico', category: 'Glúteos', primary: 'Glúteo médio',
    secondary: ['Glúteo máximo', 'Core'], equipment: 'Miniband', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Coloque o miniband acima dos joelhos, pés confortáveis e tronco alto.',
    execution: ['Afaste os joelhos contra o elástico sem inclinar o tronco.', 'Pause na abertura confortável.', 'Retorne devagar mantendo a tensão.'],
    breathing: 'Expire ao abrir e inspire ao voltar.',
    commonMistakes: ['Deixar os joelhos colapsarem na volta', 'Usar balanço', 'Colocar o elástico em local desconfortável'],
    beginnersTips: ['Comece sentada em um banco se ficar mais estável.', 'Use resistência leve e movimentos lentos.'],
    easierAlternative: 'Abdução deitado de lado sem elástico.', easierId: 'side-lying-leg-raise', substitutes: ['hip-abduction', 'side-lying-leg-raise', 'glute-bridge'],
  },
  'single-leg-calf-raise': {
    id: 'single-leg-calf-raise', name: 'Panturrilha unilateral', category: 'Pernas', primary: 'Gastrocnêmio',
    secondary: ['Sóleo'], equipment: 'Degrau e apoio firme', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Apoie o antepé em um degrau, segure em algo firme e mantenha o tornozelo alinhado.',
    execution: ['Eleve o calcanhar até o máximo confortável.', 'Pause no alto sem girar o tornozelo.', 'Desça devagar sentindo alongar a panturrilha.'],
    breathing: 'Expire ao subir e inspire ao descer.',
    commonMistakes: ['Perder o equilíbrio', 'Fazer movimentos curtos', 'Usar impulso'],
    beginnersTips: ['Comece no chão e passe ao degrau quando estiver estável.', 'Faça as mesmas repetições nos dois lados.'],
    easierAlternative: 'Elevação bilateral segurando em um apoio.', easierId: 'calf-raise', substitutes: ['calf-raise', 'seated-calf-raise'],
  },
  'seated-calf-raise': {
    id: 'seated-calf-raise', name: 'Panturrilha sentada', category: 'Pernas', primary: 'Sóleo',
    secondary: ['Gastrocnêmio'], equipment: 'Banco ou máquina', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Sente-se com a ponta dos pés apoiada, joelhos dobrados e mãos usando um apoio para estabilidade.',
    execution: ['Eleve os calcanhares mantendo a ponta dos pés apoiada.', 'Pause no alto.', 'Desça lentamente até sentir alongamento confortável.'],
    breathing: 'Expire ao subir e inspire ao descer.',
    commonMistakes: ['Quicar no final do movimento', 'Deixar os pés escorregarem', 'Fazer amplitude curta'],
    beginnersTips: ['Comece sem carga.', 'Uma anilha leve sobre as coxas só entra quando houver estabilidade.'],
    easierAlternative: 'Elevação de panturrilha sem carga em pé.', easierId: 'calf-raise', substitutes: ['calf-raise', 'single-leg-calf-raise'],
  },
  'bird-dog': {
    id: 'bird-dog', name: 'Bird dog', category: 'Core', primary: 'Core e estabilidade',
    secondary: ['Glúteos', 'Ombros'], equipment: 'Colchonete', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique em quatro apoios, mãos abaixo dos ombros, joelhos abaixo do quadril e coluna neutra.',
    execution: ['Estenda uma perna e o braço oposto sem girar o quadril.', 'Pause mantendo a respiração.', 'Volte ao centro e alterne os lados com controle.'],
    breathing: 'Expire ao estender e inspire ao retornar.',
    commonMistakes: ['Arquear a lombar', 'Abrir o quadril', 'Acelerar a troca'],
    beginnersTips: ['Comece movendo apenas uma perna por vez.', 'Use uma amplitude menor se perder o equilíbrio.'],
    easierAlternative: 'Dead bug com apenas as pernas.', easierId: 'dead-bug', substitutes: ['dead-bug', 'plank', 'pallof-press'],
  },
  'heel-tap': {
    id: 'heel-tap', name: 'Toque de calcanhar', category: 'Core', primary: 'Abdômen',
    secondary: ['Oblíquos', 'Flexores do quadril'], equipment: 'Colchonete', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Deite de costas com joelhos dobrados, pés no chão e lombar confortável contra o colchonete.',
    execution: ['Ative o abdômen e incline levemente o tronco, se for confortável.', 'Alcance um calcanhar de cada vez sem tirar os pés do chão.', 'Volte ao centro mantendo a respiração.'],
    breathing: 'Expire ao alcançar o calcanhar e inspire ao retornar.',
    commonMistakes: ['Puxar o pescoço', 'Prender a respiração', 'Forçar a lombar'],
    beginnersTips: ['Mantenha a cabeça no chão se precisar.', 'Faça movimentos pequenos e lentos.'],
    easierAlternative: 'Marcha deitada, movendo uma perna por vez.', easierId: 'dead-bug', substitutes: ['dead-bug', 'bird-dog', 'plank'],
  },
  'band-pallof-press': {
    id: 'band-pallof-press', name: 'Pallof press com elástico', category: 'Core', primary: 'Core anti-rotação',
    secondary: ['Oblíquos', 'Ombros'], equipment: 'Elástico preso na lateral', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique de lado para o ponto de ancoragem, pés afastados e mãos junto ao peito.',
    execution: ['Empurre as mãos para frente sem deixar o tronco girar.', 'Pause por um instante com os braços estendidos.', 'Traga as mãos de volta mantendo quadril e ombros alinhados.'],
    breathing: 'Expire ao estender e inspire ao retornar.',
    commonMistakes: ['Girar em direção ao elástico', 'Usar carga alta', 'Prender a respiração'],
    beginnersTips: ['Fique mais perto do ponto de ancoragem para reduzir a tensão.', 'Pratique primeiro com os braços parados junto ao peito.'],
    easierAlternative: 'Dead bug.', easierId: 'dead-bug', substitutes: ['pallof-press', 'dead-bug', 'bird-dog'],
  },
  'band-face-pull': {
    id: 'band-face-pull', name: 'Face pull com elástico', category: 'Ombros', primary: 'Deltoide posterior',
    secondary: ['Romboides', 'Manguito rotador'], equipment: 'Elástico preso na altura do rosto', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique de frente para a ancoragem, braços estendidos e ombros relaxados.',
    execution: ['Puxe o elástico em direção ao rosto abrindo as mãos.', 'Mantenha os cotovelos confortáveis e o tronco parado.', 'Retorne devagar sem perder a tensão.'],
    breathing: 'Expire na puxada e inspire na volta.',
    commonMistakes: ['Usar resistência alta', 'Encolher os ombros', 'Ancorar o elástico em local inseguro'],
    beginnersTips: ['Faça com resistência baixa e pausa curta.', 'Se sentir pinçamento, reduza a amplitude e pare.'],
    easierAlternative: 'Abertura reversa sem carga.', easierId: 'reverse-fly', substitutes: ['face-pull', 'reverse-fly', 'cable-row'],
  },
  'reverse-fly': {
    id: 'reverse-fly', name: 'Crucifixo inverso', category: 'Ombros', primary: 'Deltoide posterior',
    secondary: ['Romboides', 'Trapézio médio'], equipment: 'Halteres leves ou máquina', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Incline o tronco com coluna neutra, braços pendentes e cotovelos levemente flexionados.',
    execution: ['Abra os braços para os lados até uma altura confortável.', 'Pause sem levantar os ombros.', 'Desça devagar mantendo o pescoço relaxado.'],
    breathing: 'Expire ao abrir e inspire ao descer.',
    commonMistakes: ['Usar halteres pesados', 'Balançar o tronco', 'Encolher os ombros'],
    beginnersTips: ['Comece sem carga para encontrar o caminho.', 'A sensação deve ficar na parte posterior do ombro e costas altas.'],
    easierAlternative: 'Face pull com elástico leve.', easierId: 'band-face-pull', substitutes: ['face-pull', 'band-face-pull', 'cable-row'],
  },
  'cable-lateral-raise': {
    id: 'cable-lateral-raise', name: 'Elevação lateral na polia', category: 'Ombros', primary: 'Deltoide lateral',
    secondary: ['Trapézio superior', 'Core'], equipment: 'Polia baixa', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Fique de lado para a polia, segure a manopla com o braço mais distante e mantenha o tronco alto.',
    execution: ['Eleve o braço para o lado até a altura confortável.', 'Pause sem girar o tronco.', 'Desça lentamente mantendo tensão no cabo.'],
    breathing: 'Expire ao subir e inspire ao descer.',
    commonMistakes: ['Usar impulso', 'Elevar o ombro', 'Escolher carga alta'],
    beginnersTips: ['Segure em um apoio com a mão livre.', 'Use uma amplitude menor se o ombro perder conforto.'],
    easierAlternative: 'Elevação lateral com elástico leve.', easierId: 'band-lateral-raise', substitutes: ['lateral-raise', 'band-lateral-raise'],
  },
  'band-lateral-raise': {
    id: 'band-lateral-raise', name: 'Elevação lateral com elástico', category: 'Ombros', primary: 'Deltoide lateral',
    secondary: ['Trapézio superior', 'Core'], equipment: 'Elástico', difficulty: 'Iniciante', sourceUrl: aceLibrary,
    startingPosture: 'Pise no centro do elástico ou prenda-o abaixo, braços ao lado do corpo e ombros relaxados.',
    execution: ['Eleve os braços para os lados até a altura confortável.', 'Mantenha cotovelos levemente flexionados.', 'Desça devagar sem perder a postura.'],
    breathing: 'Expire ao subir e inspire ao descer.',
    commonMistakes: ['Balançar o corpo', 'Elevar os ombros', 'Usar resistência alta'],
    beginnersTips: ['Comece com pouca tensão.', 'Faça uma pausa curta no alto sem forçar a articulação.'],
    easierAlternative: 'Elevação lateral sem resistência.', substitutes: ['lateral-raise', 'cable-lateral-raise', 'face-pull'],
  },
};

const categoryTeaching: Record<string, ExerciseTeaching> = {
  Peito: { focus: 'Sinta o peito aproximando os braços; o ombro da frente não deve fazer todo o trabalho.', cues: ['Mantenha as escápulas apoiadas e os punhos alinhados aos antebraços.', 'Deixe os cotovelos acompanharem o movimento em um ângulo confortável.', 'Use uma volta lenta para perceber o alongamento do peito.'] },
  Costas: { focus: 'Pense em levar os cotovelos para trás ou para os bolsos e sentir as costas, não apenas os braços.', cues: ['Mantenha o peito aberto e os ombros longe das orelhas.', 'Comece o movimento pelas escápulas e não pelo impulso do tronco.', 'Pause no final da puxada e retorne com controle.'] },
  Ombros: { focus: 'Sinta o deltoide trabalhando sem deixar o trapézio tomar conta do movimento.', cues: ['Mantenha as costelas organizadas e o pescoço relaxado.', 'Gire os cotovelos suavemente para acompanhar a linha dos punhos.', 'Prefira uma amplitude confortável a subir com os ombros encolhidos.'] },
  Braços: { focus: 'Concentre a sensação no músculo do braço; o cotovelo fica estável enquanto o antebraço se move.', cues: ['Evite balançar o tronco para criar impulso.', 'Mantenha os punhos alinhados e controle especialmente a descida.', 'Pare antes de perder a posição do cotovelo ou do ombro.'] },
  Pernas: { focus: 'Sinta a coxa empurrando o chão ou a plataforma, com joelhos acompanhando a direção dos pés.', cues: ['Distribua o peso pelo meio do pé e mantenha os calcanhares apoiados.', 'Desça somente até onde a lombar e os joelhos permanecem confortáveis.', 'Suba sem travar os joelhos com força.'] },
  Posterior: { focus: 'Sinta a parte de trás da coxa alongar e contrair; a lombar não deve ser a protagonista.', cues: ['Leve o quadril para trás nas dobradiças e mantenha a coluna longa.', 'Mantenha a carga próxima ao corpo quando houver peso.', 'Reduza a amplitude se a coluna começar a arredondar.'] },
  Glúteos: { focus: 'Pense em empurrar o chão e apertar os glúteos no final, sem compensar arqueando a lombar.', cues: ['Mantenha joelhos alinhados com os pés e abdômen levemente ativo.', 'Faça uma pausa curta no ponto de maior contração.', 'Controle o retorno em vez de deixar a carga despencar.'] },
  Core: { focus: 'Sinta o abdômen mantendo o tronco estável; não é preciso fazer o movimento rápido para funcionar.', cues: ['Expire na parte mais difícil e continue respirando.', 'Mantenha costelas e quadril alinhados.', 'Diminua a amplitude ou apoie os joelhos antes de perder o controle.'] },
};

const exerciseTeaching: Record<string, ExerciseTeaching> = {
  'chest-press': { focus: 'Pressione com o peito e pense em aproximar os braços; se a frente do ombro dominar, reduza a carga.', cues: ['Ajuste as alças no meio do peito.', 'Cotovelos acompanham as mãos, sem abrir a 90°.', 'Volte até sentir o peito alongar sem perder as costas no apoio.'] },
  'cable-row': { focus: 'Puxe pelos cotovelos e procure sentir o meio das costas entre as escápulas.', cues: ['Comece aproximando as escápulas sem encolher os ombros.', 'Leve as mãos ao umbigo e mantenha o tronco estável.', 'Retorne devagar até os braços estenderem.'] },
  'lat-pulldown': { focus: 'Pense em colocar os cotovelos nos bolsos e sentir as laterais das costas.', cues: ['Mantenha o peito alto e a barra na frente do corpo.', 'Não puxe atrás da nuca nem transforme o movimento em balanço.', 'Suba controlando até sentir alongar o latíssimo.'] },
  'shoulder-press': { focus: 'Empurre usando os deltoides e mantenha as costelas baixas para não arquear a lombar.', cues: ['Deixe os cotovelos apontarem levemente para a frente.', 'Punhos ficam sobre os cotovelos durante a subida.', 'Pare antes de travar os cotovelos.'] },
  'triceps-pushdown': { focus: 'Sinta a parte de trás do braço; somente o antebraço deve se mover.', cues: ['Mantenha os cotovelos colados ao tronco.', 'Abra levemente a corda no final sem girar o ombro.', 'Suba lentamente até o cotovelo ficar confortável.'] },
  'dead-bug': { focus: 'Sinta o abdômen impedindo a lombar de arquear enquanto braços e pernas se afastam.', cues: ['Expire antes de estender o braço e a perna opostos.', 'Use menor amplitude se a lombar sair do chão.', 'Mantenha o quadril parado e alterne sem pressa.'] },
  'leg-press': { focus: 'Sinta principalmente a frente da coxa empurrando a plataforma, com glúteos ajudando.', cues: ['Joelhos acompanham a linha dos pés, sem cair para dentro.', 'Desça até o ponto em que lombar e quadril continuam apoiados.', 'Empurre pelo meio do pé sem travar os joelhos.'] },
  'leg-curl': { focus: 'Procure a contração atrás da coxa, mantendo o quadril pesado no assento.', cues: ['Alinhe o eixo da máquina com o joelho.', 'Faça uma pausa curta quando a almofada chegar perto.', 'Conte dois segundos no retorno.'] },
  'goblet-squat': { focus: 'Sinta coxas e glúteos; o halter junto ao peito ajuda a manter o tronco organizado.', cues: ['Mantenha o peso no meio dos pés e os calcanhares no chão.', 'Joelhos acompanham os dedos dos pés.', 'Use um banco como limite de profundidade enquanto aprende.'] },
  'hip-thrust': { focus: 'Contraia os glúteos no topo e imagine aproximar o púbis do umbigo, sem jogar a lombar para trás.', cues: ['Mantenha o queixo levemente recolhido.', 'Pés ficam onde a canela chega perto da vertical no topo.', 'Pause um segundo antes de descer devagar.'] },
  'calf-raise': { focus: 'Sinta a panturrilha alongar embaixo e apertar no alto, sem quicar.', cues: ['Suba pelo dedão e pelo segundo dedo sem deixar o tornozelo tombar.', 'Pause no alto e desça até uma amplitude confortável.', 'Use apoio para equilibrar e manter o movimento lento.'] },
  'plank': { focus: 'Sinta o abdômen e os glúteos mantendo o corpo inteiro firme, sem deixar a lombar ceder.', cues: ['Empurre o chão com os antebraços sem encolher os ombros.', 'Mantenha o olhar no chão e respire curto e contínuo.', 'Apoie os joelhos se a linha do quadril começar a quebrar.'] },
  'incline-press': { focus: 'Pressione com o peito superior e mantenha os ombros encaixados no banco.', cues: ['Halteres sobem sobre os cotovelos.', 'Deixe os cotovelos em uma diagonal confortável, não totalmente abertos.', 'Desça controlando e sem bater os halteres.'] },
  'face-pull': { focus: 'Sinta a parte posterior dos ombros e as costas altas; pense em girar os cotovelos para fora.', cues: ['Puxe a corda na direção do rosto, separando as mãos.', 'Mantenha os ombros longe das orelhas.', 'Use pouca carga e pare se houver pinçamento.'] },
  'dumbbell-curl': { focus: 'Sinta o bíceps encurtar sem deixar o ombro avançar.', cues: ['Mantenha o cotovelo próximo ao corpo.', 'Gire a palma para cima apenas dentro do movimento confortável.', 'Desça totalmente com controle antes de alternar.'] },
  'overhead-triceps': { focus: 'Sinta o alongamento e a contração na parte de trás do braço, com os cotovelos apontando para frente.', cues: ['Mantenha os braços relativamente parados.', 'Não abra os cotovelos para ganhar amplitude.', 'Use uma carga menor e mantenha as costelas sob controle.'] },
  'pallof-press': { focus: 'Sinta o abdômen resistindo à rotação do cabo ou elástico.', cues: ['Quadril e ombros ficam apontados para a frente.', 'Estenda as mãos sem girar o tronco.', 'Afaste-se menos do ponto de ancoragem se perder o alinhamento.'] },
  'romanian-deadlift': { focus: 'Sinta o posterior alongar enquanto o quadril vai para trás; termine apertando glúteos.', cues: ['Mantenha os halteres raspando perto das pernas.', 'Joelhos ficam levemente destravados, não agachados.', 'Pare a descida quando a coluna quiser arredondar.'] },
  'leg-extension': { focus: 'Sinta a frente da coxa estender o joelho, sem chutar a carga.', cues: ['Alinhe eixo da máquina e joelho.', 'Suba em ritmo controlado e pause sem travar.', 'Desça sem deixar as placas baterem.'] },
  'hip-abduction': { focus: 'Sinta a lateral do glúteo trabalhar; abra o suficiente para manter o tronco parado.', cues: ['Mantenha a lombar e as costas apoiadas.', 'Faça uma pausa na abertura.', 'Controle a volta e não deixe as placas baterem.'] },
  'assisted-pullup': { focus: 'Pense em levar o peito para as mãos e sentir as laterais das costas.', cues: ['Comece deprimindo os ombros antes de puxar.', 'Mantenha o corpo quieto sobre o apoio.', 'Use mais assistência se não conseguir descer devagar.'] },
  'cable-curl': { focus: 'Sinta o bíceps sob tensão contínua, inclusive na volta do cabo.', cues: ['Fique estável e não incline o tronco para trás.', 'Cotovelos permanecem próximos ao corpo.', 'Pare antes de perder o controle do punho.'] },
  'chest-supported-row': { focus: 'Sinta as costas puxando os halteres, com o peito apoiado para evitar impulso.', cues: ['Conduza pelos cotovelos, não pelos punhos.', 'Não levante os ombros em direção às orelhas.', 'Desça até quase estender os braços.'] },
  'hack-squat': { focus: 'Sinta a coxa empurrar a plataforma enquanto costas e quadril permanecem apoiados.', cues: ['Aponte joelhos para a mesma direção dos pés.', 'Use apenas a profundidade que mantém o apoio.', 'Suba sem travar os joelhos.'] },
  'lateral-raise': { focus: 'Sinta a lateral do ombro; conduza o movimento com os cotovelos e deixe as mãos acompanharem.', cues: ['Mantenha ombros longe das orelhas.', 'Suba só até a altura confortável.', 'Use halteres leves e desça em dois segundos.'] },
};

export const getExerciseTeaching = (exercise: Exercise): ExerciseTeaching => exerciseTeaching[exercise.id] ?? categoryTeaching[exercise.category] ?? {
  focus: `Sinta o trabalho em ${exercise.primary.toLowerCase()} e mantenha o movimento lento e confortável.`,
  cues: ['Mantenha o tronco estável e a amplitude sem dor.', 'Expire na parte mais difícil e inspire no retorno.', 'Reduza a carga ou a amplitude se perder a técnica.'],
};

const exerciseGifBase = 'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0';
const exerciseGifSource = 'https://jahelcuadrado.github.io/ExerciseGymGifsDB/';

const exerciseGif = (path: string, label: string): ExerciseGif => ({
  url: `${exerciseGifBase}/${path}.gif`,
  label,
  sourceUrl: exerciseGifSource,
  sourceLabel: 'Exercise Gym GIFs DB',
});

const youtubeSearch = (term: string): string => `https://www.youtube.com/results?search_query=${encodeURIComponent(`${term} execução correta vídeo curto`)}`;

const gifPair = (firstPath: string, firstLabel: string, secondPath: string, secondLabel: string, term: string): ExerciseMedia => ({
  gifs: [exerciseGif(firstPath, firstLabel), exerciseGif(secondPath, secondLabel)],
  youtubeUrl: youtubeSearch(term),
});

export const exerciseMedia: Record<string, ExerciseMedia> = {
  'chest-press': gifPair('pectorals/lever-chest-press', 'Execução principal', 'pectorals/lever-chest-press-0577', 'Variação de máquina', 'machine chest press'),
  'cable-row': gifPair('upper-back/cable-seated-row', 'Execução principal', 'upper-back/cable-rope-seated-row', 'Variação com corda', 'seated cable row'),
  'lat-pulldown': gifPair('lats/cable-pulldown', 'Pegada tradicional', 'lats/cable-lat-pulldown-full-range-of-motion', 'Amplitude completa', 'lat pulldown'),
  'shoulder-press': gifPair('delts/lever-shoulder-press', 'Execução principal', 'delts/lever-shoulder-press-v-2', 'Variação de máquina', 'machine shoulder press'),
  'triceps-pushdown': gifPair('triceps/cable-triceps-pushdown-v-bar', 'Barra em V', 'triceps/cable-triceps-pushdown-v-bar-with-arm-blaster', 'Com apoio de braços', 'cable triceps pushdown'),
  'dead-bug': gifPair('abs/dead-bug', 'Execução principal', 'abs/bodyweight-incline-side-plank', 'Variação de estabilidade do core', 'dead bug exercise'),
  'leg-press': gifPair('glutes/sled-45-leg-press', 'Visão principal', 'glutes/sled-45-leg-press-side-pov', 'Visão lateral', '45 degree leg press'),
  'leg-curl': gifPair('hamstrings/lever-seated-leg-curl', 'Flexora sentada', 'hamstrings/lever-lying-leg-curl', 'Flexora deitada', 'seated leg curl machine'),
  'goblet-squat': gifPair('quads/dumbbell-goblet-squat', 'Com halter', 'glutes/kettlebell-goblet-squat', 'Com kettlebell', 'goblet squat'),
  'hip-thrust': gifPair('glutes/resistance-band-hip-thrusts-on-knees-female', 'Elevação de quadril', 'glutes/glute-bridge-two-legs-on-bench-male', 'Variação de ponte apoiada', 'hip thrust'),
  'calf-raise': gifPair('calves/bodyweight-standing-calf-raise', 'Sem carga', 'calves/barbell-standing-calf-raise', 'Com carga', 'standing calf raise'),
  'plank': gifPair('abs/power-point-plank', 'Prancha estável', 'abs/front-plank-with-twist', 'Variação com movimento', 'front plank'),
  'incline-press': gifPair('pectorals/dumbbell-incline-bench-press', 'Com halteres', 'pectorals/barbell-incline-bench-press', 'Com barra', 'dumbbell incline press'),
  'face-pull': gifPair('delts/cable-standing-cross-over-high-reverse-fly', 'Puxada alta para o rosto', 'delts/band-reverse-fly', 'Variação com elástico', 'face pull com corda'),
  'dumbbell-curl': gifPair('biceps/dumbbell-alternate-biceps-curl', 'Rosca alternada', 'biceps/dumbbell-standing-biceps-curl', 'Rosca simultânea', 'alternating dumbbell biceps curl'),
  'overhead-triceps': gifPair('triceps/cable-overhead-triceps-extension-rope-attachment', 'Com corda na polia', 'triceps/dumbbell-standing-triceps-extension', 'Com halter', 'overhead cable triceps extension'),
  'pallof-press': gifPair('abs/band-horizontal-pallof-press', 'Empurrada horizontal', 'abs/band-vertical-pallof-press', 'Variação vertical', 'band pallof press'),
  'romanian-deadlift': gifPair('glutes/dumbbell-romanian-deadlift', 'Com halteres', 'glutes/barbell-romanian-deadlift', 'Com barra', 'dumbbell romanian deadlift'),
  'leg-extension': gifPair('quads/lever-leg-extension', 'Na máquina', 'quads/resistance-band-leg-extension', 'Variação com elástico', 'leg extension machine'),
  'hip-abduction': gifPair('abductors/lever-seated-hip-abduction', 'Na máquina', 'abductors/resistance-band-seated-hip-abduction', 'Sentada com elástico', 'hip abduction machine'),
  'assisted-pullup': gifPair('lats/assisted-pull-up', 'Pegada confortável', 'lats/assisted-parallel-close-grip-pull-up', 'Pegada paralela', 'assisted pull up machine'),
  'cable-curl': gifPair('biceps/cable-curl', 'Com barra', 'biceps/cable-hammer-curl-with-rope', 'Com corda', 'cable biceps curl'),
  'chest-supported-row': gifPair('upper-back/dumbbell-reverse-grip-incline-bench-one-arm-row', 'Remada apoiada unilateral', 'upper-back/lever-seated-row', 'Remada sentada', 'chest supported dumbbell row'),
  'hack-squat': gifPair('glutes/sled-hack-squat', 'Hack tradicional', 'glutes/smith-hack-squat', 'Variação no Smith', 'hack squat'),
  'lateral-raise': gifPair('delts/dumbbell-lateral-raise', 'Com halteres', 'delts/cable-lateral-raise', 'Na polia', 'dumbbell lateral raise'),
  'dumbbell-bench-press': gifPair('pectorals/dumbbell-bench-press', 'Com halteres', 'pectorals/barbell-bench-press', 'Com barra', 'dumbbell bench press'),
  'incline-push-up': gifPair('pectorals/incline-push-up', 'Apoio alto', 'pectorals/incline-push-up-on-box', 'Apoio em caixa', 'incline push up'),
  'cable-chest-fly': gifPair('pectorals/cable-standing-fly', 'Crucifixo na polia', 'pectorals/cable-upper-chest-crossovers', 'Variação cruzada', 'cable chest fly'),
  'one-arm-dumbbell-row': gifPair('upper-back/dumbbell-one-arm-bent-over-row', 'Remada unilateral', 'upper-back/dumbbell-reverse-grip-incline-bench-one-arm-row', 'Remada apoiada', 'one arm dumbbell row'),
  'band-row': gifPair('upper-back/band-one-arm-twisting-seated-row', 'Remada com elástico', 'upper-back/bodyweight-standing-row-with-towel', 'Variação sem máquina', 'resistance band row'),
  'band-lat-pulldown': gifPair('lats/band-close-grip-pulldown', 'Pegada fechada', 'lats/band-underhand-pulldown', 'Pegada supinada', 'band lat pulldown'),
  'dumbbell-shoulder-press': gifPair('delts/dumbbell-seated-shoulder-press', 'Sentado com dois halteres', 'delts/dumbbell-one-arm-shoulder-press', 'Unilateral', 'dumbbell shoulder press'),
  'band-shoulder-press': gifPair('delts/band-shoulder-press', 'Em pé', 'delts/resistance-band-seated-shoulder-press', 'Sentado', 'band shoulder press'),
  'band-triceps-extension': gifPair('triceps/band-side-triceps-extension', 'Com elástico', 'triceps/bodyweight-kneeling-triceps-extension', 'Variação ajoelhada', 'band triceps extension'),
  'dumbbell-triceps-kickback': gifPair('triceps/dumbbell-standing-bent-over-one-arm-triceps-extension', 'Unilateral', 'triceps/dumbbell-standing-bent-over-two-arm-triceps-extension', 'Com os dois braços', 'dumbbell triceps kickback'),
  'hammer-curl': gifPair('biceps/dumbbell-hammer-curl', 'Rosca martelo', 'biceps/dumbbell-hammer-curl-v-2', 'Variação de rosca martelo', 'hammer curl'),
  'band-curl': gifPair('biceps/band-alternating-biceps-curl', 'Alternada', 'biceps/resistance-band-seated-biceps-curl', 'Sentada', 'band biceps curl'),
  'box-squat': gifPair('glutes/dumbbell-bench-squat', 'Agachamento para banco', 'glutes/potty-squat-with-support', 'Agachamento com apoio', 'box squat beginner'),
  'step-up': gifPair('glutes/dumbbell-step-up', 'Com halteres', 'glutes/band-step-up', 'Com elástico', 'step up exercise'),
  'reverse-lunge': gifPair('glutes/dumbbell-rear-lunge', 'Com halteres', 'glutes/barbell-rear-lunge', 'Com barra', 'reverse lunge'),
  'stability-ball-curl': gifPair('glutes/exercise-ball-one-legged-diagonal-kick-hamstring-curl', 'Com bola', 'hamstrings/lever-lying-leg-curl', 'Variação na máquina', 'stability ball leg curl'),
  'cable-pull-through': gifPair('glutes/cable-pull-through-with-rope', 'Com corda', 'glutes/cable-deadlift', 'Variação de dobradiça na polia', 'cable pull through'),
  'bodyweight-hip-hinge': gifPair('glutes/bench-hip-extension', 'Com apoio', 'glutes/lever-seated-good-morning', 'Variação de dobradiça', 'bodyweight hip hinge'),
  'glute-bridge': gifPair('glutes/low-glute-bridge-on-floor', 'No chão', 'glutes/glute-bridge-march', 'Com marcha', 'glute bridge'),
  'side-lying-leg-raise': gifPair('abductors/side-hip-abduction', 'De lado', 'abductors/straight-leg-outer-hip-abductor', 'Perna estendida', 'side lying leg raise'),
  'band-abduction': gifPair('abductors/resistance-band-seated-hip-abduction', 'Sentada', 'abductors/side-hip-abduction', 'Sem elástico', 'band hip abduction'),
  'single-leg-calf-raise': gifPair('calves/band-single-leg-calf-raise', 'Com elástico', 'calves/dumbbell-single-leg-calf-raise', 'Com halter', 'single leg calf raise'),
  'seated-calf-raise': gifPair('calves/lever-seated-calf-raise', 'Na máquina', 'calves/dumbbell-seated-calf-raise', 'Com halter', 'seated calf raise'),
  'bird-dog': gifPair('abs/dead-bug', 'Controle alternado', 'abs/bodyweight-incline-side-plank', 'Estabilidade do core', 'bird dog exercise'),
  'heel-tap': gifPair('abs/alternate-heel-touchers', 'Toque alternado', 'abs/dead-bug', 'Variação de controle', 'heel taps abs'),
  'band-pallof-press': gifPair('abs/band-horizontal-pallof-press', 'Horizontal', 'abs/band-vertical-pallof-press', 'Vertical', 'band pallof press'),
  'band-face-pull': gifPair('delts/band-reverse-fly', 'Com elástico', 'delts/cable-standing-cross-over-high-reverse-fly', 'Na polia', 'band face pull'),
  'reverse-fly': gifPair('delts/dumbbell-reverse-fly', 'Com halteres', 'delts/band-reverse-fly', 'Com elástico', 'reverse fly'),
  'cable-lateral-raise': gifPair('delts/cable-lateral-raise', 'Na polia', 'delts/cable-one-arm-lateral-raise', 'Unilateral', 'cable lateral raise'),
  'band-lateral-raise': gifPair('delts/band-front-lateral-raise', 'Com elástico', 'delts/dumbbell-lateral-raise', 'Variação com halteres', 'band lateral raise'),
};

export const getExerciseMedia = (exerciseId: string): ExerciseMedia | undefined => exerciseMedia[exerciseId];

const ex = (exerciseId: string, sets: number, reps: string, rest: number, cue: string): WorkoutExercise => ({ exerciseId, sets, reps, rest, cue });
const cardio = (name: string, duration: string, intensity: string, instructions: string): CardioOption => ({ name, duration, intensity, instructions });

export const workoutPlans: Record<Person, WorkoutDay[]> = {
  breno: [
    {
      id: 'breno-upper-a', person: 'breno', title: 'Base de cima', label: 'Peito + costas', objective: 'Construir força de base no tronco com movimentos estáveis.',
      muscleGroups: ['Peito', 'Costas', 'Ombros', 'Tríceps', 'Core'], duration: '60–70 min', warmup: ['5–7 min de caminhada ou bike leve', '1 série leve de cada primeiro exercício', 'Mobilidade suave de ombros e coluna torácica'], finish: '2–3 min caminhando devagar e respiração confortável.', safety: 'Mantenha 2–3 repetições “na reserva” nas primeiras semanas.',
      exercises: [ex('chest-press', 3, '8–12', 90, 'Empurre com o peito aberto, sem travar os cotovelos.'), ex('cable-row', 3, '8–12', 90, 'Puxe pelos cotovelos e pause as escápulas.'), ex('lat-pulldown', 3, '8–12', 90, 'Traga a barra ao peito, nunca atrás da nuca.'), ex('shoulder-press', 2, '10–12', 75, 'Costas apoiadas e costelas controladas.'), ex('triceps-pushdown', 2, '10–15', 60, 'Cotovelos quietos ao lado do corpo.'), ex('dead-bug', 3, '8–10/lado', 45, 'Só aumente a amplitude se a lombar ficar estável.')],
      cardio: [cardio('Caminhada confortável', '8–12 min', 'Leve a moderada', 'Mantenha um ritmo em que consiga falar frases curtas; incline só se for confortável.'), cardio('Bike ergométrica', '8–12 min', 'Leve a moderada', 'Pedale de forma contínua, sem sprint, e termine com a respiração controlada.')],
    },
    {
      id: 'breno-lower-a', person: 'breno', title: 'Pernas base', label: 'Quadríceps + glúteos', objective: 'Treinar pernas completas com ritmo controlado e segurança.',
      muscleGroups: ['Quadríceps', 'Posterior', 'Glúteos', 'Panturrilhas', 'Core'], duration: '58–68 min', warmup: ['5–7 min de bike leve', '8 agachamentos para um banco, sem carga', '1 série de adaptação no leg press'], finish: 'Caminhada leve até a respiração normalizar; alongamento suave opcional.', safety: 'A profundidade é limitada pela sua postura, não pela pressa de descer mais.',
      exercises: [ex('leg-press', 3, '8–12', 120, 'Joelhos acompanham a linha dos pés.'), ex('leg-curl', 3, '10–12', 90, 'Quadril permanece apoiado.'), ex('goblet-squat', 2, '10–12', 90, 'Use o banco como referência.'), ex('hip-thrust', 2, '10–12', 90, 'Finalize com glúteos, não com a lombar.'), ex('calf-raise', 2, '12–15', 60, 'Pausa curta no alto.'), ex('plank', 3, '20–40 s', 45, 'Respire sem deixar o quadril cair.')],
      cardio: [cardio('Bike ergométrica', '8–12 min', 'Moderada confortável', 'Use resistência baixa ou média e mantenha um ritmo constante, sem precisar correr.'), cardio('Elíptico', '8–10 min', 'Leve a moderada', 'Faça passadas suaves e reduza o ritmo aos poucos nos últimos minutos.')],
    },
    {
      id: 'breno-upper-b', person: 'breno', title: 'Tronco completo', label: 'Costas + braços', objective: 'Reforçar puxadas, empurradas e estabilidade dos ombros.',
      muscleGroups: ['Costas', 'Peito', 'Bíceps', 'Tríceps', 'Ombros', 'Core'], duration: '60–70 min', warmup: ['5 min de elíptico leve', 'Movimentos circulares controlados para ombros', '1 série leve de supino e remada'], finish: 'Respiração leve e mobilidade de peito/ombros sem forçar.', safety: 'Prefira repetir com técnica consistente a aumentar carga a cada sessão.',
      exercises: [ex('incline-press', 3, '8–12', 90, 'Halteres sobem sobre os cotovelos.'), ex('cable-row', 3, '8–12', 90, 'Tronco firme e retorno lento.'), ex('chest-supported-row', 2, '10–12', 75, 'Mantenha o peito apoiado.'), ex('face-pull', 2, '12–15', 60, 'Leve a corda ao rosto sem encolher os ombros.'), ex('dumbbell-curl', 2, '10–12', 60, 'Cotovelo fica próximo ao corpo.'), ex('overhead-triceps', 2, '10–12', 60, 'Amplitude confortável para o ombro.'), ex('pallof-press', 2, '10/lado', 45, 'Resista à rotação do tronco.')],
      cardio: [cardio('Caminhada plana', '8–12 min', 'Leve a moderada', 'Caminhe em ritmo contínuo e confortável, sem transformar a finalização em corrida.'), cardio('Bike ergométrica', '8–12 min', 'Leve a moderada', 'Pedale com cadência confortável e ajuste o banco antes de começar.')],
    },
    {
      id: 'breno-lower-b', person: 'breno', title: 'Pernas posterior', label: 'Posterior + pernas', objective: 'Dar atenção à cadeia posterior e completar o trabalho de pernas.',
      muscleGroups: ['Posterior', 'Glúteos', 'Quadríceps', 'Panturrilhas', 'Core'], duration: '56–66 min', warmup: ['5–7 min de caminhada inclinada leve', 'Dobradiça de quadril sem carga', '1 série leve de flexora'], finish: 'Caminhe 3 minutos e faça alongamentos confortáveis, sem dor.', safety: 'No romeno, a amplitude termina quando a coluna quer arredondar.',
      exercises: [ex('romanian-deadlift', 3, '8–12', 120, 'Quadril para trás; halteres próximos às pernas.'), ex('hack-squat', 3, '8–12', 120, 'Use a amplitude que mantém costas apoiadas.'), ex('leg-extension', 2, '10–15', 75, 'Subida controlada e sem travar.'), ex('hip-abduction', 2, '12–15', 60, 'Segure um segundo na abertura.'), ex('calf-raise', 2, '12–15', 60, 'Movimento completo e estável.'), ex('dead-bug', 3, '8–10/lado', 45, 'Costelas e lombar continuam organizadas.')],
      cardio: [cardio('Caminhada com leve inclinação', '8–12 min', 'Leve a moderada', 'Use inclinação pequena somente se joelhos e lombar estiverem confortáveis.'), cardio('Elíptico', '8–10 min', 'Leve a moderada', 'Mantenha passadas fáceis e encerre diminuindo o ritmo gradualmente.')],
    },
  ],
  leticia: [
    {
      id: 'leticia-lower-a', person: 'leticia', title: 'Pernas & glúteos', label: 'Quadríceps + glúteos', objective: 'Começar a semana com foco em pernas, estabilidade e um aeróbico simples para apoiar o emagrecimento.',
      muscleGroups: ['Quadríceps', 'Glúteos', 'Posterior', 'Core'], duration: '50–60 min', warmup: ['5–7 min de bike leve', 'Agachamentos para banco sem carga', '1 série leve de leg press'], finish: 'Caminhada leve e mobilidade confortável de quadril.', safety: 'Comece com cargas leves; a técnica e a constância valem mais que terminar exausta.',
      exercises: [ex('leg-press', 2, '10–14', 90, 'Pés firmes e joelhos acompanham os pés.'), ex('hip-thrust', 2, '10–14', 75, 'Contraia glúteos sem arquear a lombar.'), ex('leg-extension', 2, '12–15', 60, 'Amplitude confortável e controlada.'), ex('hip-abduction', 2, '12–15', 45, 'Não deixe a carga bater.'), ex('dead-bug', 2, '8–10/lado', 45, 'Lombar fica estável no chão.')],
      cardio: [cardio('Caminhada confortável', '10–15 min', 'Moderada confortável', 'Mantenha um ritmo em que consiga falar frases curtas; não é preciso correr.'), cardio('Bike ergométrica', '10–12 min', 'Leve a moderada', 'Pedale de forma contínua, com resistência confortável e sem sprint.')],
    },
    {
      id: 'leticia-upper-a', person: 'leticia', title: 'Parte de cima', label: 'Costas + peito', objective: 'Fortalecer o corpo todo com uma sequência fácil de acompanhar e cardio leve no final.',
      muscleGroups: ['Costas', 'Peito', 'Ombros', 'Bíceps', 'Tríceps'], duration: '50–60 min', warmup: ['5 min de elíptico leve', 'Mobilidade suave de ombros', '1 série de adaptação nas primeiras máquinas'], finish: 'Reduza o ritmo e faça respiração tranquila por 2–3 min.', safety: 'Mantenha a carga leve o suficiente para falar frases curtas durante as pausas.',
      exercises: [ex('lat-pulldown', 2, '10–14', 75, 'Barra na frente do corpo e peito alto.'), ex('chest-press', 2, '10–14', 75, 'Empurre sem elevar os ombros.'), ex('cable-row', 2, '10–14', 60, 'Sem balançar o tronco.'), ex('shoulder-press', 2, '10–12', 60, 'Mantenha as costas apoiadas.'), ex('cable-curl', 2, '12–15', 45, 'Cotovelos estáveis.'), ex('triceps-pushdown', 2, '12–15', 45, 'Controle a volta da corda.')],
      cardio: [cardio('Elíptico', '10–15 min', 'Moderada confortável', 'Mantenha passadas suaves e um ritmo em que consiga falar frases curtas.'), cardio('Caminhada plana', '10–15 min', 'Leve a moderada', 'Caminhe continuamente e use os últimos minutos para desacelerar.')],
    },
    {
      id: 'leticia-lower-b', person: 'leticia', title: 'Posterior & glúteos', label: 'Posterior + glúteos', objective: 'Trabalhar a cadeia posterior com boa amplitude, controle e volume acessível.',
      muscleGroups: ['Posterior', 'Glúteos', 'Quadríceps', 'Panturrilhas', 'Core'], duration: '52–62 min', warmup: ['5–7 min de caminhada leve', 'Dobradiça do quadril sem carga', '1 série leve de flexora e hip thrust'], finish: 'Caminhe até a respiração acalmar e alongue sem insistir na dor.', safety: 'No romeno, desça somente enquanto consegue manter coluna longa; reduza a carga se a postura mudar.',
      exercises: [ex('romanian-deadlift', 2, '10–12', 90, 'Quadril recua, halteres ficam próximos.'), ex('leg-curl', 2, '10–14', 75, 'Pausa curta na flexão.'), ex('hip-thrust', 2, '10–14', 75, 'Queixo levemente recolhido.'), ex('hack-squat', 2, '10–14', 75, 'Controle a descida na máquina.'), ex('calf-raise', 2, '12–15', 45, 'Suba sem girar os tornozelos.'), ex('plank', 2, '20–35 s', 45, 'Respire de forma contínua.')],
      cardio: [cardio('Bike ergométrica', '10–12 min', 'Leve a moderada', 'Pedale em ritmo estável e confortável, sem sprintar após o treino de pernas.'), cardio('Caminhada plana', '8–12 min', 'Leve', 'Caminhe para desacelerar e pare se a técnica da passada mudar por cansaço.')],
    },
    {
      id: 'leticia-full-body', person: 'leticia', title: 'Corpo todo & core', label: 'Full body', objective: 'Fechar a semana com uma rotina simples, corpo todo e cardio moderado para apoiar o emagrecimento.',
      muscleGroups: ['Pernas', 'Glúteos', 'Peito', 'Costas', 'Ombros', 'Core'], duration: '50–60 min', warmup: ['5 min de bike ou caminhada', 'Agachamento sem carga e mobilidade leve', '1 série de adaptação no primeiro exercício'], finish: 'Caminhe devagar e escolha alongamentos leves se forem agradáveis.', safety: 'Este é um treino de consolidação: termine sentindo que poderia fazer mais uma repetição boa.',
      exercises: [ex('goblet-squat', 2, '10–14', 75, 'Use um banco como referência.'), ex('incline-press', 2, '10–14', 75, 'Punhos sobre os cotovelos.'), ex('lat-pulldown', 2, '10–14', 75, 'Puxe com os cotovelos.'), ex('hip-abduction', 2, '12–15', 45, 'Segure a abertura.'), ex('face-pull', 2, '12–15', 45, 'Movimento leve e preciso.'), ex('pallof-press', 2, '10/lado', 45, 'Quadril permanece alinhado.')],
      cardio: [cardio('Caminhada confortável', '10–15 min', 'Moderada confortável', 'Caminhe em ritmo contínuo e mantenha a respiração controlada; não precisa correr.'), cardio('Bike ergométrica', '10–12 min', 'Leve a moderada', 'Pedale sem sprint e finalize reduzindo a resistência aos poucos.')],
    },
  ],
};

export const personMeta: Record<Person, { name: string; shortName: string; pronoun: string; accent: 'lime' | 'coral'; focus: string; avatar: string }> = {
  breno: { name: 'Breno', shortName: 'BR', pronoun: 'seu', accent: 'lime', focus: 'Força geral com atenção para peito, costas, braços e pernas.', avatar: 'B' },
  leticia: { name: 'Letícia', shortName: 'LE', pronoun: 'seu', accent: 'coral', focus: 'Corpo todo com prioridade para pernas, glúteos, posterior e core, com cardio leve para apoiar o emagrecimento.', avatar: 'L' },
};

export const weekdayFromDate = (date: Date): Weekday => {
  const values: Weekday[] = ['dom', 'seg', 'ter', 'qua', 'qui', 'sex', 'sab'];
  return values[date.getDay()];
};

export const formatDate = (date: Date): string => new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short' }).format(date).replace('.', '');

export const formatFullDate = (date: Date): string => new Intl.DateTimeFormat('pt-BR', { weekday: 'long', day: '2-digit', month: 'long' }).format(date);
